// Direção visual: Casa de Areia — luxo rústico contemporâneo, branco quente, areia, champanhe e verde profundo; foco B2C em chegada e hospitalidade.
import { useEffect, useState } from "react";
import { ArrowDown, ArrowUpRight, Check, ChevronDown, Instagram, Menu, MoveRight, X } from "lucide-react";

const whatsapp = "https://wa.me/5573991681630?text=Ol%C3%A1!%20Gostaria%20de%20reservar%20um%20transfer%20privativo%20com%20a%20Nativos%20Experiences.";
const heroImage = "/manus-storage/nativos-trancoso-hero_c2d6fb6a.jpg";
const arrivalImage = "/manus-storage/nativos-trancoso-arrival_d7daf1dd.jpg";
const coastImage = "/manus-storage/nativos-trancoso-coast_6362d1a5.jpg";
const interiorImage = "/manus-storage/nativos-trancoso-interior_8463c2a6.jpg";
const markImage = "/manus-storage/nativos-trancoso-mark_396fc119.png";

const services = [
  { no: "01", title: "Transfer privativo", text: "Do Aeroporto de Porto Seguro ou Terravista até sua hospedagem, com monitoramento de voo, recepção organizada e motorista local.", image: arrivalImage },
  { no: "02", title: "Motorista à disposição", text: "Seu carro, seu tempo. Para circular entre praias, restaurantes, villas e tudo o que você quiser descobrir na Costa do Descobrimento.", image: interiorImage },
  { no: "03", title: "Concierge Trancoso", text: "Restaurantes, praias, barcos e experiências escolhidas para os seus dias — com o olhar de quem conhece o destino por dentro.", image: coastImage },
];
const fleet = [["Executiva", "Jeep Compass ou similar", "4"], ["Luxo híbrida", "GWM Haval H6 ou similar", "4"], ["Premium", "CAOA Chery Tiggo 8 Pro ou similar", "6"], ["Elite", "Toyota SW4 ou GWM H9", "6"], ["Exclusive", "BMW iX1 · 100% elétrica", "4"], ["Blindado", "Mercedes-Benz GLE 400d", "4"], ["Van Executiva", "Mercedes-Benz Sprinter", "9 / 15"], ["Van Longa", "Mercedes-Benz Sprinter Longa", "19"]];
const destinations = ["Trancoso", "Arraial d’Ajuda", "Praia do Espelho", "Caraíva", "Santo André", "Corumbau", "Itacaré"];
const faqs = [["Como funciona o transfer do aeroporto para Trancoso?", "Você informa o seu voo e a hospedagem. Nós monitoramos a chegada, organizamos a recepção e deixamos o veículo preparado para levar você com conforto e discrição."], ["Vocês atendem o Aeroporto Terravista?", "Sim. Atendemos passageiros de aviação particular no Aeroporto Terravista, com receptivo e mobilidade privativa. Valores sob consulta."], ["O que está incluído no transfer?", "Motorista local, veículo privativo, apoio com bagagens, água mineral, água de coco e snacks conforme a operação. Bebê conforto, cadeirinha e assento elevado podem ser solicitados sem custo adicional."], ["Quais regiões vocês atendem?", "Trancoso e os principais destinos da Costa do Descobrimento, incluindo Arraial d’Ajuda, Praia do Espelho, Caraíva, Santo André, Corumbau e Itacaré."]];
const scrollTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
function Logo() { return <a className="brand" href="#top" aria-label="Nativos Experiences"><img src={markImage} alt="" /><span><b>nativos</b><small>experiences</small></span></a>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false); const [faq, setFaq] = useState<number | null>(null);
  useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add("is-visible")), { threshold: .12 }); document.querySelectorAll(".reveal").forEach((el) => observer.observe(el)); return () => observer.disconnect(); }, []);
  return <main id="top" className="site-shell sand-theme">
    <header className="nav-wrap"><div className="nav-inner"><Logo /><nav className={`nav-links ${menuOpen ? "nav-links--open" : ""}`} aria-label="Navegação principal"><a href="#servicos" onClick={() => setMenuOpen(false)}>Experiências</a><a href="#frota" onClick={() => setMenuOpen(false)}>Conforto</a><a href="#destinos" onClick={() => setMenuOpen(false)}>Destinos</a><a href="#contato" onClick={() => setMenuOpen(false)}>Contato</a></nav><a className="nav-cta" href={whatsapp} target="_blank" rel="noreferrer">Reservar transfer <ArrowUpRight size={15} /></a><button className="menu-toggle" onClick={() => setMenuOpen((v) => !v)} aria-label="Abrir menu">{menuOpen ? <X /> : <Menu />}</button></div></header>

    <section className="hero sand-hero" aria-labelledby="hero-title"><img className="hero-image" src={heroImage} alt="SUV premium em uma estrada costeira da Bahia" /><div className="hero-shade" /><div className="hero-content"><p className="eyebrow light"><span className="eyebrow-dot" /> Trancoso · Bahia</p><h1 id="hero-title">A viagem começa<br />quando você é <em>recebido.</em></h1><div className="hero-bottom"><p className="hero-intro">Transfer privativo e concierge para chegar a Trancoso com conforto, discrição e o tempo que a Bahia pede.</p><a className="hero-action" href={whatsapp} target="_blank" rel="noreferrer">Reservar meu transfer <MoveRight size={18} /></a></div></div><div className="hero-meta"><span>DESDE 2015</span><span className="meta-line" /><span>TRANCOSO / BAHIA</span></div><div className="scroll-cue"><ArrowDown size={17} /><span>descubra o destino</span></div></section>

    <section className="welcome section-light" aria-labelledby="welcome-title"><div className="section-index">N / 01</div><div className="welcome-grid"><div className="welcome-image reveal"><img src={arrivalImage} alt="Chegada de hóspedes em uma pousada de Trancoso" /><span>Uma chegada tranquila muda tudo.</span></div><div className="welcome-copy reveal"><p className="eyebrow dark"><span className="eyebrow-dot" /> Somos de Trancoso</p><h2 id="welcome-title">Você informa o voo.<br />A gente cuida <em>do resto.</em></h2><p>Conhecemos os caminhos, os horários e o ritmo desse lugar. Por isso, cada transfer é pensado para que você desça do avião e já sinta que as férias começaram.</p><a className="text-link" href={whatsapp} target="_blank" rel="noreferrer">Falar com um concierge <ArrowUpRight size={17} /></a></div></div></section>

    <section id="servicos" className="experiences section-sand" aria-labelledby="services-title"><div className="section-head reveal"><div><p className="eyebrow dark"><span className="eyebrow-dot" /> Do primeiro quilômetro ao último pôr do sol</p><h2 id="services-title">Tudo para viver<br /><em>Trancoso no seu ritmo.</em></h2></div><p className="section-note">Uma equipe local, um atendimento próximo e o cuidado de deixar cada detalhe no lugar.</p></div><div className="experience-list">{services.map((item) => <article className="experience-card reveal" key={item.no}><div className="experience-image-wrap"><img src={item.image} alt={item.title} /><span className="card-number">{item.no}</span><span className="card-arrow"><ArrowUpRight size={18} /></span></div><div className="experience-info"><div><p className="card-region">Nativos Experiences</p><h3>{item.title}</h3></div><p className="card-description">{item.text}</p></div></article>)}</div></section>

    <section id="frota" className="fleet-section section-dark" aria-labelledby="fleet-title"><div className="section-index">N / 02</div><div className="fleet-head reveal"><p className="eyebrow light"><span className="eyebrow-dot" /> Conforto que combina com a viagem</p><h2 id="fleet-title">Escolha como<br /><em>quer chegar.</em></h2><p>Da categoria executiva ao blindado, a frota é dimensionada para o seu grupo, sua bagagem e seu jeito de viajar. O modelo específico é confirmado conforme disponibilidade.</p></div><div className="fleet-grid">{fleet.map(([name, model, capacity], i) => <div className="fleet-item reveal" key={name}><span className="step-no">0{i + 1}</span><div><h3>{name}</h3><p>{model}</p></div><span className="fleet-pax">{capacity}<small> lugares</small></span></div>)}</div><div className="fleet-note"><Check size={16} /><span>Água, água de coco, snacks e apoio com bagagens. Starlink em veículos e rotas compatíveis.</span></div></section>

    <section id="destinos" className="destinations section-light" aria-labelledby="destinations-title"><div className="destination-image reveal"><img src={coastImage} alt="Praia tranquila na Costa do Descobrimento" /><span>o caminho também é parte</span></div><div className="destination-copy reveal"><p className="eyebrow dark"><span className="eyebrow-dot" /> Entre o mar e a mata</p><h2 id="destinations-title">Trancoso é a base.<br /><em>A Bahia é o convite.</em></h2><p>Para além do Quadrado, existem praias, vilas e caminhos que merecem tempo. Conte onde você quer ir e a gente desenha a melhor forma de chegar.</p><div className="destination-list">{destinations.map((destination, i) => <span key={destination}><i>0{i + 1}</i>{destination}</span>)}</div><a className="dark-button" href={whatsapp} target="_blank" rel="noreferrer">Planejar minha rota <ArrowUpRight size={17} /></a></div></section>

    <section className="hospitality section-sand" aria-labelledby="hospitality-title"><div className="hospitality-grid"><div className="hospitality-copy reveal"><p className="eyebrow dark"><span className="eyebrow-dot" /> Hospitalidade a bordo</p><h2 id="hospitality-title">O cuidado aparece<br /><em>nos detalhes.</em></h2><p>Um carro limpo, uma recepção pontual, água gelada, uma cadeirinha para o seu filho. O luxo está em não precisar pedir o que já foi pensado.</p><div className="care-list"><span><Check size={15} /> Motorista local e recepção organizada</span><span><Check size={15} /> Água mineral e água de coco</span><span><Check size={15} /> Bebê conforto e cadeirinha sob solicitação</span><span><Check size={15} /> Carregadores e apoio com bagagens</span></div></div><div className="hospitality-image reveal"><img src={interiorImage} alt="Detalhes de conforto no interior de veículo premium" /><span>feito para você relaxar</span></div></div></section>

    <section className="faq section-light" aria-labelledby="faq-title"><div className="section-head reveal"><div><p className="eyebrow dark"><span className="eyebrow-dot" /> Antes de embarcar</p><h2 id="faq-title">Tudo certo<br /><em>antes de partir.</em></h2></div><p className="section-note">Se a sua dúvida não estiver aqui, nosso concierge responde diretamente.</p></div><div className="faq-list">{faqs.map(([question, answer], i) => <div className={`faq-item ${faq === i ? "faq-item--open" : ""}`} key={question}><button onClick={() => setFaq(faq === i ? null : i)} aria-expanded={faq === i}><span>0{i + 1}</span><strong>{question}</strong><ChevronDown size={18} /></button>{faq === i && <p>{answer}</p>}</div>)}</div></section>

    <section id="contato" className="contact sand-contact" aria-labelledby="contact-title"><div className="contact-orbit" /><div className="section-index dark-index">N / 03</div><div className="contact-grid"><div className="contact-copy reveal"><p className="eyebrow dark"><span className="eyebrow-dot" /> A sua chegada começa aqui</p><h2 id="contact-title">Vamos cuidar<br />da sua <em>chegada?</em></h2><p>Envie seu voo, sua hospedagem e o que você gostaria de viver em Trancoso. A gente responde com a melhor forma de fazer acontecer.</p><div className="contact-details"><span><Check size={15} /> Atendimento humano</span><span><Check size={15} /> Transfer privativo sob medida</span><span><Check size={15} /> WhatsApp +55 73 99168-1630</span></div></div><div className="contact-card reveal"><span className="card-region">CONCIERGE NATIVOS</span><h3>Fale com a gente</h3><p>Para reservar um transfer ou planejar seus dias na Bahia.</p><a className="form-submit" href={whatsapp} target="_blank" rel="noreferrer">Abrir conversa no WhatsApp <ArrowUpRight size={18} /></a><a className="contact-email" href="mailto:contato@nativosexperiences.com">contato@nativosexperiences.com</a></div></div></section>

    <footer className="footer section-dark"><Logo /><div className="footer-center"><span>Chegar bem é parte da viagem.</span><span>Trancoso, Bahia.</span></div><div className="footer-right"><a href={whatsapp} target="_blank" rel="noreferrer">WhatsApp <ArrowUpRight size={15} /></a><a href="https://instagram.com/nativosexperiences" target="_blank" rel="noreferrer"><Instagram size={16} /> Instagram</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Nativos Experiences</span><span>Transfer privativo · Concierge · Trancoso</span></div></footer>
  </main>;
}
