// Direção visual: Casa de Areia — páginas de serviço B2C com luz, textura, narrativa local e CTA direto para o concierge.
import { useEffect } from "react";
import { ArrowLeft, ArrowUpRight, Check, Instagram } from "lucide-react";
import { Link } from "wouter";

const whatsapp = "https://wa.me/5573991681630?text=Ol%C3%A1!%20Gostaria%20de%20falar%20com%20um%20concierge%20da%20Nativos%20Experiences.";
const data = {
  airport: { kicker:"TRANSFER · AEROPORTO", title:"Do aeroporto para Trancoso, com tudo já cuidado.", intro:"Recepção privativa no Aeroporto de Porto Seguro, Terravista ou Outeiro das Brisas. Você desembarca. A Nativos faz o resto.", image:"/manus-storage/nativos-trancoso-arrival_d7daf1dd.jpg", heading:"Três portas de entrada.\nUma chegada tranquila.", body:"Atendemos os principais aeroportos da região com motorista local, veículo dedicado e apoio com bagagens. No Porto Seguro (BPS), orientamos a melhor rota entre balsa e BR-367 conforme o momento. No Terravista (SBTV), o trajeto até o Quadrado leva cerca de 15 minutos. No Outeiro das Brisas (SNEC), você está a poucos minutos da Praia do Espelho.", items:["Aeroporto de Porto Seguro (BPS) · via balsa ou BR-367","Aeroporto Terravista (SBTV) · aviação executiva","Outeiro das Brisas (SNEC) · próximo à Praia do Espelho","Monitoramento de voo e motorista aguardando"], cta:"Reservar transfer de aeroporto" },
  transfer: { kicker:"TRANSFER · TRANCOSO E REGIÃO", title:"O caminho até o destino também pode ser leve.", intro:"Transfers privativos entre aeroportos, pousadas, villas, praias e cidades da Costa do Descobrimento.", image:"/manus-storage/nativos-trancoso-coast_6362d1a5.jpg", heading:"Você escolhe o lugar.\nA gente conhece o caminho.", body:"De Trancoso a Arraial d’Ajuda, Praia do Espelho, Caraíva, Santo André, Corumbau ou Itacaré. Também cuidamos dos deslocamentos internos: pousada, Quadrado, restaurante, praia ou festa. Tudo de forma privativa e personalizada.", items:["Trancoso ↔ Arraial d’Ajuda","Trancoso ↔ Praia do Espelho","Trancoso ↔ Caraíva","Rotas especiais sob consulta"], cta:"Planejar meu trajeto" },
  fleet: { kicker:"FROTA · CONFORTO", title:"O carro certo para o jeito que você viaja.", intro:"Categorias executivas, premium, elétricas, vans e blindado — sempre com motorista local.", image:"/manus-storage/nativos-trancoso-interior_8463c2a6.jpg", heading:"Conforto não é excesso.\nÉ poder relaxar.", body:"A Nativos trabalha com dez categorias de veículos. A categoria é garantida; o modelo de referência pode variar conforme disponibilidade. Para escolher bem, consideramos passageiros, bagagem, trajeto e o nível de conforto que você espera.", items:["Executiva, Luxo, Premium e Elite","Exclusive · BMW iX1 100% elétrica","Vans para 9, 15 ou até 19 passageiros","Blindado Mercedes-Benz GLE 400d"], cta:"Consultar categoria" },
  armored: { kicker:"TRANSFER · BLINDADO", title:"Segurança reforçada, sem abrir mão da discrição.", intro:"O Mercedes-Benz GLE 400d blindado está disponível sob demanda para quem precisa de uma camada adicional de proteção em Trancoso e região.", image:"/manus-storage/nativos-trancoso-hero_c2d6fb6a.jpg", heading:"Proteção para seguir\ncom tranquilidade.", body:"Executivos, famílias, artistas, autoridades e eventos podem solicitar o veículo blindado com antecedência. A operação permanece discreta do primeiro embarque ao último retorno, com motorista local e atendimento personalizado.", items:["Mercedes-Benz GLE 400d","Até 4 passageiros","Disponível sob demanda","Reserva antecipada recomendada"], cta:"Solicitar transfer blindado" },
  chauffeur: { kicker:"MOTORISTA À DISPOSIÇÃO", title:"Seu dia, no seu ritmo.", intro:"Um motorista particular e um veículo dedicado para você circular sem depender de horários ou negociar cada trajeto.", image:"/manus-storage/nativos-trancoso-arrival_d7daf1dd.jpg", heading:"Mais tempo para viver.\nMenos tempo organizando.", body:"Escolha o período que faz sentido para a sua estadia: 4h, 8h, 12h ou 24h. O motorista leva, aguarda e retorna quando você decidir — para um dia de praia, um jantar ou uma sequência de compromissos.", items:["Períodos de 4h, 8h, 12h ou 24h","Veículo 100% dedicado","Motorista local e discreto","Ideal para praias, restaurantes e eventos"], cta:"Consultar motorista à disposição" },
  concierge: { kicker:"CONCIERGE · TRANCOSO", title:"Para viver Trancoso sem perder tempo procurando.", intro:"Restaurantes, praias, barcos, villas e experiências escolhidas para os seus dias — com um concierge que conhece a região por dentro.", image:"/manus-storage/nativos-trancoso-coast_6362d1a5.jpg", heading:"O que você quiser viver.\nA gente ajuda a acontecer.", body:"Do jantar na villa ao passeio de barco, do chef particular à massagem depois da praia. O concierge Nativos coordena os detalhes da sua estadia com olhar local, discrição e uma conversa direta pelo WhatsApp.", items:["Restaurantes e beach clubs","Barcos, praias e passeios privativos","Chef, compras e serviços para a villa","Bem-estar, beleza e experiências"], cta:"Falar com concierge" },
  events: { kicker:"CASAMENTOS E EVENTOS", title:"A celebração merece uma chegada à altura.", intro:"Transporte de convidados, noivos, artistas e staff para casamentos, festas privadas e eventos em Trancoso e região.", image:"/manus-storage/nativos-trancoso-hero_c2d6fb6a.jpg", heading:"O seu evento acontece.\nA logística fica com a gente.", body:"Coordenamos vans, SUVs, veículos especiais e horários escalonados para que cada convidado saiba onde embarcar e chegue no tempo certo. Para Praia do Espelho, Caraíva e locais de difícil acesso, planejamos a operação conforme o terreno e o roteiro.", items:["Casamentos íntimos e grandes celebrações","Transporte de convidados e padrinhos","Artistas, staff, fornecedores e equipamentos","Vans, apoio e blindado sob consulta"], cta:"Solicitar orçamento de evento" },
  destinations: { kicker:"DESTINOS · BAHIA", title:"Trancoso é o ponto de partida.", intro:"Praias, vilas e caminhos da Costa do Descobrimento para descobrir com um motorista que sabe quando ir — e por onde.", image:"/manus-storage/nativos-trancoso-coast_6362d1a5.jpg", heading:"A Bahia tem muitos ritmos.\nEscolha o seu.", body:"Faça um passeio de dia inteiro, combine uma praia com um almoço ou crie uma rota entre destinos. O carro é privativo, o roteiro é seu e o caminho é cuidado pela equipe local.", items:["Trancoso · Quadrado, praias e villas","Arraial d’Ajuda · história e mirantes","Praia do Espelho · praia e almoço","Caraíva, Santo André e Corumbau"], cta:"Escolher meu destino" },
  about: { kicker:"SOBRE · NATIVOS EXPERIENCES", title:"Nascemos em Trancoso para fazer você se sentir em casa.", intro:"Desde 2015, cuidamos de chegadas, deslocamentos e detalhes de estadias com discrição, pontualidade e conhecimento local.", image:"/manus-storage/nativos-trancoso-arrival_d7daf1dd.jpg", heading:"Conhecer o destino\né cuidar melhor.", body:"A Nativos nasceu levando amigos do aeroporto ao Quadrado. Hoje, uma equipe local atende famílias, viajantes, executivos e eventos que valorizam a tranquilidade de ter alguém de confiança no caminho.", items:["Atendimento privativo, um cliente por vez","Motoristas locais e discretos","Curadoria de quem vive em Trancoso","Suporte pessoal pelo WhatsApp"], cta:"Conversar com a Nativos" },
  booking: { kicker:"RESERVA · NATIVOS EXPERIENCES", title:"Sua chegada começa com uma conversa.", intro:"Envie o voo, a hospedagem e o que você precisa. Um concierge confirma veículo, motorista, disponibilidade e valor.", image:"/manus-storage/nativos-trancoso-interior_8463c2a6.jpg", heading:"Você informa os detalhes.\nA gente cuida do caminho.", body:"Para solicitar um transfer, conte a origem, o destino, a data, o horário, o número de passageiros e a bagagem. Se houver voo, envie o número para acompanharmos a chegada. Se não souber qual categoria escolher, recomendamos a melhor opção.", items:["Transfer de aeroporto ou entre cidades","Motorista à disposição","Concierge e experiências","Eventos e casamentos"], cta:"Abrir reserva no WhatsApp" },
};

type ServiceType = keyof typeof data;
export default function ServicePage({ type }: { type: ServiceType }) { const page = data[type]; useEffect(() => { document.title = `${page.title} | Nativos Experiences`; const meta = document.querySelector('meta[name="description"]'); meta?.setAttribute("content", page.intro); }, [page]); return <main className="service-page sand-theme"><header className="nav-wrap"><div className="nav-inner"><a href="/" className="brand"><img src="/manus-storage/nativos-trancoso-mark_396fc119.png" alt="" /><span><b>nativos</b><small>experiences</small></span></a><nav className="nav-links"><a href="/transfer-aeroporto">Transfer aeroporto</a><a href="/concierge">Concierge</a><a href="/casamentos-e-eventos">Eventos</a><a href="/destinos">Destinos</a></nav><a className="nav-cta" href={whatsapp} target="_blank" rel="noreferrer">Falar com concierge <ArrowUpRight size={15} /></a></div></header><section className="service-hero"><img src={page.image} alt="" /><div className="service-hero-shade" /><div className="service-hero-content"><a href="/" className="back-link"><ArrowLeft size={15} /> Voltar à Nativos</a><p className="eyebrow light"><span className="eyebrow-dot" /> {page.kicker}</p><h1>{page.title}</h1><p>{page.intro}</p><a className="hero-action" href={whatsapp} target="_blank" rel="noreferrer">{page.cta} <MoveArrow /></a></div></section><section className="service-body section-light"><div className="service-body-grid"><div className="service-copy"><p className="eyebrow dark"><span className="eyebrow-dot" /> Nativos Experiences</p><h2>{page.heading.split("\n").map((line, i) => <span key={line}>{line}{i === 0 && <br />}</span>)}</h2><p>{page.body}</p><a className="dark-button" href={whatsapp} target="_blank" rel="noreferrer">{page.cta} <ArrowUpRight size={17} /></a></div><div className="service-facts"><span className="facts-label">O que você pode esperar</span>{page.items.map((item, i) => <div className="service-fact" key={item}><span>0{i + 1}</span><strong>{item}</strong><Check size={16} /></div>)}</div></div></section><footer className="footer section-dark"><a href="/" className="brand"><img src="/manus-storage/nativos-trancoso-mark_396fc119.png" alt="" /><span><b>nativos</b><small>experiences</small></span></a><div className="footer-center"><span>Chegar bem é parte da viagem.</span><span>Trancoso, Bahia.</span></div><div className="footer-right"><a href={whatsapp} target="_blank" rel="noreferrer">WhatsApp <ArrowUpRight size={15} /></a><a href="https://instagram.com/nativosexperiences" target="_blank" rel="noreferrer"><Instagram size={16} /> Instagram</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Nativos Experiences</span><span>Transfer privativo · Concierge · Trancoso</span></div></footer></main>; }
function MoveArrow() { return <ArrowUpRight size={17} />; }
