// Casa de Areia: chrome compartilhado com navegação hierárquica e conversão direta.
import { MobileMenu } from "@/components/MobileMenu";
import { ServicesMenu } from "@/components/ServicesMenu";

export const whatsapp = "https://wa.me/5573991681630?text=Ol%C3%A1!%20Gostaria%20de%20falar%20com%20um%20concierge%20da%20Nativos%20Experiences.";
export const partnershipWhatsapp = "https://wa.me/5573991681630?text=Ol%C3%A1!%20Gostaria%20de%20conhecer%20as%20parcerias%20da%20Nativos%20Experiences.";
export const eventWhatsapp = "https://wa.me/5573991681630?text=Ol%C3%A1!%20Gostaria%20de%20solicitar%20um%20or%C3%A7amento%20de%20evento.%20Data%3A%20%7C%20N%C3%BAmero%20de%20convidados%3A%20%7C%20Tipo%20de%20evento%3A%20";
const mark = "https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/usTPVzSokKzdeTWC.png";

type Locale = "pt-BR" | "en";
type NavItem = { label: string; path: string };
type ChromeProps = { locale?: Locale };
type ChromeCopy = { home: string; nav: NavItem[]; menuServices: NavItem[]; services: NavItem[]; company: NavItem[]; cta: string; footer: string; place: string; instagram: string; whatsapp: string };

const copy: Record<Locale, ChromeCopy> = {
  "pt-BR": { home: "/", nav: [{ label: "Sobre", path: "sobre-nativos" }, { label: "Frota", path: "frota" }, { label: "Concierge", path: "concierge-trancoso" }, { label: "Casamentos e Eventos", path: "casamentos-e-eventos" }, { label: "Parcerias", path: "parcerias" }], menuServices: [{ label: "Transfer Aeroporto", path: "transfer-aeroporto" }, { label: "Transfer Blindado", path: "transfer-blindado" }, { label: "Motorista à Disposição", path: "motorista-a-disposicao" }, { label: "Passeios", path: "passeios" }], services: [{ label: "Transfer Aeroporto", path: "transfer-aeroporto" }, { label: "Transfer Blindado", path: "transfer-blindado" }, { label: "Motorista à Disposição", path: "motorista-a-disposicao" }, { label: "Passeios", path: "passeios" }], company: [{ label: "Sobre", path: "sobre-nativos" }, { label: "Frota", path: "frota" }, { label: "Concierge", path: "concierge-trancoso" }, { label: "Casamentos e Eventos", path: "casamentos-e-eventos" }, { label: "Parcerias", path: "parcerias" }, { label: "Destinos", path: "destinos" }], cta: "Falar com concierge", footer: "Chegar bem é parte da viagem.", place: "Trancoso, Bahia.", instagram: "Instagram", whatsapp: "WhatsApp" },
  en: { home: "/en", nav: [{ label: "About", path: "sobre-nativos" }, { label: "Fleet", path: "frota" }, { label: "Concierge", path: "concierge-trancoso" }, { label: "Weddings & Events", path: "casamentos-e-eventos" }, { label: "Partners", path: "parcerias" }], menuServices: [{ label: "Airport Transfer", path: "transfer-aeroporto" }, { label: "Armored Transfer", path: "transfer-blindado" }, { label: "Private Chauffeur", path: "motorista-a-disposicao" }, { label: "Day Trips", path: "passeios" }], services: [{ label: "Airport Transfer", path: "transfer-aeroporto" }, { label: "Armored Transfer", path: "transfer-blindado" }, { label: "Private Chauffeur", path: "motorista-a-disposicao" }, { label: "Day Trips", path: "passeios" }], company: [{ label: "About", path: "sobre-nativos" }, { label: "Fleet", path: "frota" }, { label: "Concierge", path: "concierge-trancoso" }, { label: "Weddings & Events", path: "casamentos-e-eventos" }, { label: "Partners", path: "parcerias" }, { label: "Destinations", path: "destinos" }], cta: "Talk to a concierge", footer: "Arriving well is part of the journey.", place: "Trancoso, Bahia.", instagram: "Instagram", whatsapp: "WhatsApp" }
};

export function Brand({ locale = "pt-BR" }: ChromeProps) { const t = copy[locale]; return <a className="brand" href={t.home}><img src={mark} alt="" /><span><b>nativos</b><small>experiences</small></span></a>; }
export function Header({ locale = "pt-BR" }: ChromeProps) { const t = copy[locale]; const prefix = locale === "en" ? "/en" : ""; return <header className="nav-wrap"><div className="nav-inner"><Brand locale={locale} /><nav className="nav-links" aria-label={locale === "en" ? "Main navigation" : "Navegação principal"}>{t.nav.slice(0, 1).map((item) => <a key={item.path} href={`${prefix}/${item.path}`}>{item.label}</a>)}<ServicesMenu label={locale === "en" ? "Services" : "Serviços"} items={t.menuServices} prefix={prefix} />{t.nav.slice(1).map((item) => <a key={item.path} href={`${prefix}/${item.path}`}>{item.label}</a>)}</nav><div className="nav-actions"><a className="nav-cta" href={whatsapp} target="_blank" rel="noreferrer">{t.cta}</a><MobileMenu items={t.nav} serviceItems={t.menuServices} prefix={prefix} cta={t.cta} ctaHref={whatsapp} /></div></div></header>; }
export function Footer({ locale = "pt-BR" }: ChromeProps) { const t = copy[locale]; const prefix = locale === "en" ? "/en" : ""; return <footer className="footer section-dark"><div className="footer-top"><Brand locale={locale} /><div className="footer-center"><span>{t.footer}</span><span>{t.place}</span></div><div className="footer-navigation"><div><strong>{locale === "en" ? "Services" : "Serviços"}</strong>{t.services.map((item) => <a key={item.path} href={`${prefix}/${item.path}`}>{item.label}</a>)}</div><div><strong>{locale === "en" ? "Explore" : "Explore"}</strong>{t.company.map((item) => <a key={item.path} href={`${prefix}/${item.path}`}>{item.label}</a>)}</div></div><div className="footer-right"><a href={whatsapp} target="_blank" rel="noreferrer">{t.whatsapp}</a><a href="https://instagram.com/nativosexperiences" target="_blank" rel="noreferrer">{t.instagram}</a><a href="mailto:contato@nativosexperiences.com">contato@nativosexperiences.com</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Nativos Experiences</span><span>{locale === "en" ? "Private transfer · Concierge · Trancoso" : "Transfer privativo · Concierge · Trancoso"}</span><span>CNPJ 22.891.018/0001-63</span></div></footer>; }
export function WhatsAppButton({ label, href = whatsapp }: { label: string; href?: string }) { return <a className="dark-button" href={href} target="_blank" rel="noreferrer">{label}</a>; }

// Style reminder: keep Casa de Areia hierarchy, restrained navigation and generous breathing room around the CTA.
