// Casa de Areia: chrome compartilhado, agora com navegação SSR específica para português e inglês.
export const whatsapp = "https://wa.me/5573991681630?text=Ol%C3%A1!%20Gostaria%20de%20falar%20com%20um%20concierge%20da%20Nativos%20Experiences.";
export const partnershipWhatsapp = "https://wa.me/5573991681630?text=Ol%C3%A1!%20Gostaria%20de%20conhecer%20as%20parcerias%20da%20Nativos%20Experiences.";
export const eventWhatsapp = "https://wa.me/5573991681630?text=Ol%C3%A1!%20Gostaria%20de%20solicitar%20um%20or%C3%A7amento%20de%20evento.%20Data%3A%20%7C%20N%C3%BAmero%20de%20convidados%3A%20%7C%20Tipo%20de%20evento%3A%20";
const mark = "https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/usTPVzSokKzdeTWC.png";

type Locale = "pt-BR" | "en";
type ChromeProps = { locale?: Locale };
const copy = { "pt-BR": { home:"/", nav:["Transfer aeroporto","Concierge","Eventos","Destinos","Parcerias"], paths:["transfer-aeroporto","concierge","casamentos-e-eventos","destinos","parcerias"], cta:"Falar com concierge", footer:"Chegar bem é parte da viagem.", place:"Trancoso, Bahia.", instagram:"Instagram", whatsapp:"WhatsApp", back:"Voltar à Nativos", lang:"English", switchPath:(slug?: string) => slug ? `/en/${slug}` : "/en" }, en: { home:"/en", nav:["Airport transfer","Concierge","Events","Destinations","Partners"], paths:["transfer-aeroporto","concierge-trancoso","casamentos-e-eventos","destinos","parcerias"], cta:"Talk to a concierge", footer:"Arriving well is part of the journey.", place:"Trancoso, Bahia.", instagram:"Instagram", whatsapp:"WhatsApp", back:"Back to Nativos", lang:"Português", switchPath:(slug?: string) => slug ? `/${slug}` : "/" } } as const;

export function Brand({ locale = "pt-BR" }: ChromeProps) { const t = copy[locale]; return <a className="brand" href={t.home}><img src={mark} alt="" /><span><b>nativos</b><small>experiences</small></span></a>; }
export function Header({ locale = "pt-BR" }: ChromeProps) { const t = copy[locale]; return <header className="nav-wrap"><div className="nav-inner"><Brand locale={locale} /><nav className="nav-links" aria-label={locale === "en" ? "Main navigation" : "Navegação principal"}>{t.nav.map((label, index) => <a key={label} href={locale === "en" ? `/en/${t.paths[index]}` : `/${t.paths[index]}`}>{label}</a>)}</nav><div className="nav-actions"><a className="locale-link" href={t.switchPath()} lang={locale === "en" ? "pt-BR" : "en"}>{t.lang}</a><a className="nav-cta" href={whatsapp} target="_blank" rel="noreferrer">{t.cta}</a></div></div></header>; }
export function Footer({ locale = "pt-BR" }: ChromeProps) { const t = copy[locale]; return <footer className="footer section-dark"><Brand locale={locale} /><div className="footer-center"><span>{t.footer}</span><span>{t.place}</span></div><div className="footer-right"><a href={whatsapp} target="_blank" rel="noreferrer">{t.whatsapp}</a><a href="https://instagram.com/nativosexperiences" target="_blank" rel="noreferrer">{t.instagram}</a><a href="mailto:contato@nativosexperiences.com">contato@nativosexperiences.com</a><a href={t.switchPath()} lang={locale === "en" ? "pt-BR" : "en"}>{t.lang}</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Nativos Experiences</span><span>{locale === "en" ? "Private transfer · Concierge · Trancoso" : "Transfer privativo · Concierge · Trancoso"}</span><span>CNPJ 22.891.018/0001-63</span></div></footer>; }
export function WhatsAppButton({ label, href = whatsapp }: { label: string; href?: string }) { return <a className="dark-button" href={href} target="_blank" rel="noreferrer">{label}</a>; }
