// Casa de Areia: chrome compartilhado, com navegação curta e CTA de conversão para o cliente final.
export const whatsapp = "https://wa.me/5573991681630?text=Ol%C3%A1!%20Gostaria%20de%20falar%20com%20um%20concierge%20da%20Nativos%20Experiences.";
export const partnershipWhatsapp = "https://wa.me/5573991681630?text=Ol%C3%A1!%20Gostaria%20de%20conhecer%20as%20parcerias%20da%20Nativos%20Experiences.";
export const eventWhatsapp = "https://wa.me/5573991681630?text=Ol%C3%A1!%20Gostaria%20de%20solicitar%20um%20or%C3%A7amento%20de%20evento.%20Data%3A%20%7C%20N%C3%BAmero%20de%20convidados%3A%20%7C%20Tipo%20de%20evento%3A%20";
const mark = "https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/usTPVzSokKzdeTWC.png";

export function Brand() { return <a className="brand" href="/"><img src={mark} alt="" /><span><b>nativos</b><small>experiences</small></span></a>; }
export function Header() { return <header className="nav-wrap"><div className="nav-inner"><Brand /><nav className="nav-links" aria-label="Navegação principal"><a href="/transfer-aeroporto">Transfer aeroporto</a><a href="/concierge">Concierge</a><a href="/casamentos-e-eventos">Eventos</a><a href="/destinos">Destinos</a><a href="/parcerias">Parcerias</a></nav><a className="nav-cta" href={whatsapp} target="_blank" rel="noreferrer">Falar com concierge</a></div></header>; }
export function Footer() { return <footer className="footer section-dark"><Brand /><div className="footer-center"><span>Chegar bem é parte da viagem.</span><span>Trancoso, Bahia.</span></div><div className="footer-right"><a href={whatsapp} target="_blank" rel="noreferrer">WhatsApp</a><a href="https://instagram.com/nativosexperiences" target="_blank" rel="noreferrer">Instagram</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Nativos Experiences</span><span>Transfer privativo · Concierge · Trancoso</span><span>CNPJ 22.891.018/0001-63</span></div></footer>; }
export function WhatsAppButton({ label, href = whatsapp }: { label: string; href?: string }) { return <a className="dark-button" href={href} target="_blank" rel="noreferrer">{label}</a>; }
