// Fonte única de conteúdo: fatos operacionais organizados para jornadas B2C e uma entrada B2B discreta.
export type ServiceType = "airport" | "transfer" | "portoSeguro" | "tours" | "fleet" | "armored" | "chauffeur" | "concierge" | "events" | "destinations" | "about" | "booking" | "partnerships";
export type Faq = { question: string; answer: string };
export type Differentiator = { kind: "water" | "coconut" | "snacks" | "wipes" | "sanitizer" | "chargers" | "signal" | "family"; label: string; text: string };
export type DifferentiatorContent = { eyebrow: string; title: string; emphasis: string; description?: string };
export type ImageFit = "cover" | "contain";
export type ImagePresentation = { imageFocus?: string; imageFocusMobile?: string; imageFit?: ImageFit; imageFitMobile?: ImageFit; imageBackground?: string };
export type ServiceData = { type: ServiceType; slug: string; aliases: string[]; kicker: string; title: string; intro: string; image: string; imageMobile?: string; imageAlt: string; heading: string; body: string; items: string[]; cta: string; faqs: Faq[]; seoTitle?: string; seoDescription?: string; opening?: string; relatedSlugs?: string[]; differentiators?: Differentiator[] } & ImagePresentation;
const img = { hero:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/IXsbtKKPZyLFaNZk.webp", fleetOriginal:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/ngYUjyrErIzmCAtY.webp", arrival:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/bJeJxNaHowAcQwoA.jpg", coast:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/juCISiyVGtGMuEWJ.jpg", interior:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/fYDlnobOrHYCOWuB.jpg" };
const commonFaqs = [{question:"Como faço uma reserva?",answer:"Envie pelo WhatsApp a data, origem, destino, passageiros, bagagem e, se houver, o número do voo. Um concierge confirma disponibilidade, categoria e valor."},{question:"Vocês atendem crianças?",answer:"Sim. Bebê conforto, cadeirinha e assento elevado podem ser solicitados no momento da reserva, sem custo adicional."}];
export const homeHeroImage = img.hero;
export const homeWelcomeImage = "https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/zLrDzOoUTkwXaknX.webp";
export const homeServiceImages = {
  airport: { image: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/BLAidOFJuLwOGhEK.webp", imageAlt: "Aeronaves executivas no Aeroporto Terravista, próximo a Trancoso", imageFocus: "right center", imageFocusMobile: "right center", imageFit: "contain" as ImageFit, imageFitMobile: "contain" as ImageFit },
  chauffeur: { image: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/MJdtpvqcywBvshoF.webp", imageAlt: "SUV premium em deslocamento privativo em Trancoso", imageFocus: "right center", imageFocusMobile: "right center", imageFit: "contain" as ImageFit, imageFitMobile: "contain" as ImageFit },
  concierge: { image: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/cmrgvDdYfvgXvSph.webp", imageAlt: "Mesa de praia com champanhe diante do mar em Trancoso", imageFocus: "right center", imageFocusMobile: "right center", imageFit: "contain" as ImageFit, imageFitMobile: "contain" as ImageFit },
} as const;

export const differentiators: Differentiator[] = [{kind:"water",label:"Água mineral e água de coco",text:"Água mineral e água de coco a bordo."},{kind:"snacks",label:"Snacks a bordo",text:"Snacks selecionados para o trajeto."},{kind:"sanitizer",label:"Álcool em gel e lenços",text:"Álcool em gel e lenço umedecido disponíveis a bordo."},{kind:"signal",label:"Internet Starlink",text:"Conexão via satélite em veículos e rotas compatíveis."},{kind:"chargers",label:"Carregadores",text:"Carregadores para eletrônicos disponíveis a bordo."},{kind:"family",label:"Conforto para crianças",text:"Bebê conforto, cadeirinha e assento elevado sem custo adicional."}];
export const onboardDifferentiatorTypes: ServiceType[] = ["airport","transfer","portoSeguro","armored","chauffeur","events","booking","tours"];

export const differentiatorContent: Record<ServiceType | "home", DifferentiatorContent> = {
  home:{eyebrow:"O cuidado nos detalhes",title:"Uma chegada com",emphasis:"tudo no lugar.",description:"Pequenos cuidados que deixam a viagem mais leve desde o primeiro quilômetro."},
  airport:{eyebrow:"Conforto desde o desembarque",title:"A sua chegada começa",emphasis:"antes do hotel.",description:"Um serviço pensado para transformar deslocamento em acolhimento."},
  transfer:{eyebrow:"Hospitalidade no caminho",title:"Viajar pela Bahia",emphasis:"pode ser leve.",description:"Detalhes que acompanham você entre aeroportos, pousadas, praias e vilas."},
  portoSeguro:{eyebrow:"Do aeroporto ao destino",title:"O caminho de Porto Seguro",emphasis:"já começa cuidado.",description:"Conforto e atenção para atravessar a chegada a Trancoso com tranquilidade."},
  armored:{eyebrow:"Proteção com discrição",title:"Segurança sem abrir mão",emphasis:"do conforto.",description:"Uma operação reservada para quem precisa de uma camada adicional de proteção."},
  chauffeur:{eyebrow:"Liberdade para circular",title:"Seu dia, sem perder",emphasis:"nenhum detalhe.",description:"Um veículo dedicado e um motorista atento ao ritmo da sua estadia."},
  concierge:{eyebrow:"Curadoria local",title:"Trancoso fica mais simples",emphasis:"quando alguém conhece o caminho.",description:"Atenção local para organizar experiências, reservas e momentos especiais."},
  events:{eyebrow:"Logística de celebrações",title:"Cada convidado chega",emphasis:"no tempo certo.",description:"Coordenação e presença para que a operação sustente a experiência do evento."},
  fleet:{eyebrow:"Escolha com intenção",title:"O conforto certo para",emphasis:"o seu jeito de viajar.",description:"Categorias pensadas para passageiros, bagagens e diferentes momentos da viagem."},
  destinations:{eyebrow:"O caminho também importa",title:"A Bahia se revela",emphasis:"nos detalhes da rota.",description:"Apoio para descobrir destinos com tempo, conforto e olhar local."},
  tours:{eyebrow:"Um dia para descobrir",title:"O destino merece",emphasis:"o seu tempo.",description:"Passeios privativos com motorista aguardando enquanto você vive cada lugar."},
  about:{eyebrow:"A forma Nativos de receber",title:"Conhecer o destino é",emphasis:"cuidar melhor.",description:"Uma operação local guiada por proximidade, discrição e atenção."},
  booking:{eyebrow:"Antes do embarque",title:"Sua reserva começa",emphasis:"com uma conversa.",description:"Conte o que você precisa e deixe o planejamento do caminho com a nossa equipe."},
  partnerships:{eyebrow:"Operação para parceiros",title:"Confiabilidade para sustentar",emphasis:"a experiência da sua marca.",description:"Uma equipe local que executa cada deslocamento com organização e consistência."}
};
export const serviceData: Record<ServiceType, ServiceData> = {
 airport:{type:"airport",slug:"transfer-aeroporto",aliases:["transfer-aeroporto-terravista"],kicker:"TRANSFER · AEROPORTO",title:"Do aeroporto para Trancoso, com tudo já cuidado.",intro:"Recepção privativa no Aeroporto de Porto Seguro, Terravista ou Outeiro das Brisas. Você desembarca. A Nativos faz o resto.",image:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/jPyGigNXWIoKvSaN.webp",imageAlt:"Recepção de passageiros em veículo premium na chegada a Trancoso",heading:"Três portas de entrada.\nUma chegada tranquila.",body:"Atendemos os principais aeroportos da região com motorista local, veículo dedicado e apoio com bagagens. Do Aeroporto de Porto Seguro (BPS) até Trancoso, o trajeto leva de 1h15 a 2h via balsa, ou até 1h20 pela BR-367, rota terrestre sem balsa com cerca de 80 km. Do Aeroporto Terravista (SBTV) até Trancoso são aproximadamente 15 minutos, sem travessia de balsa. O Outeiro das Brisas (SNEC) atende principalmente aviação executiva ou privada com destino à Praia do Espelho e arredores.",items:["Porto Seguro (BPS) — Trancoso · 1h15 a 2h via balsa","Porto Seguro (BPS) — Trancoso · até 1h20 via BR-367","Terravista (SBTV) — Trancoso · cerca de 15 minutos","Outeiro das Brisas (SNEC) · aviação executiva para Praia do Espelho","Monitoramento de voo e motorista aguardando"],cta:"Reservar transfer de aeroporto",faqs:[{question:"Quanto tempo leva de Porto Seguro a Trancoso?",answer:"Via balsa, o trajeto costuma levar de 1h15 a 2h. Pela BR-367, sem balsa, pode levar até 1h20 em cerca de 80 km, conforme as condições da estrada."},{question:"Quanto tempo leva do Terravista até Trancoso?",answer:"O Aeroporto Terravista fica a aproximadamente 15 minutos de Trancoso e não exige travessia de balsa."},{question:"O Outeiro das Brisas atende qual tipo de chegada?",answer:"É uma porta de entrada voltada principalmente à aviação executiva ou privada com destino à Praia do Espelho e arredores."}],},
 
	 portoSeguro:{type:"portoSeguro",slug:"transfer-porto-seguro-trancoso",aliases:[],kicker:"TRANSFER · PORTO SEGURO — TRANCOSO",title:"Do Aeroporto de Porto Seguro a Trancoso, com o caminho já resolvido.",intro:"Transfer privativo entre o Aeroporto de Porto Seguro e Trancoso, com motorista local, apoio com bagagem e escolha de rota conforme o seu horário.",image:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/OCYafloFONygDrvR.webp",imageAlt:"Motorista recebendo viajantes em transfer privativo do Aeroporto de Porto Seguro para Trancoso",heading:"A porta de entrada\npara a sua Bahia.",body:"A Nativos Experiences opera transfers privativos entre o Aeroporto de Porto Seguro e Trancoso. Pela balsa, o trajeto costuma levar de 1h15 a 2h. Pela BR-367, sem travessia, pode levar até 1h20 em aproximadamente 80 km. O tempo varia conforme o trânsito, a balsa e as condições da estrada; a rota é alinhada no atendimento.",items:["Aeroporto de Porto Seguro (BPS) — Trancoso","1h15 a 2h via balsa","Até 1h20 pela BR-367, sem balsa","Motorista local e apoio com bagagens","Monitoramento de voo sob consulta"],cta:"Reservar Porto Seguro — Trancoso",faqs:[{question:"Quanto tempo leva o transfer do Aeroporto de Porto Seguro para Trancoso?",answer:"Via balsa, o trajeto costuma levar de 1h15 a 2h. Pela BR-367, sem balsa, pode levar até 1h20 em aproximadamente 80 km, conforme as condições da estrada."},{question:"A Nativos acompanha o horário do voo?",answer:"O número do voo pode ser enviado no momento da reserva para que a operação seja organizada conforme a chegada prevista."},{question:"Qual rota é usada entre Porto Seguro e Trancoso?",answer:"A rota pode ser feita via balsa ou pela BR-367, sem travessia. A melhor opção é alinhada conforme horário, trânsito e condições do caminho."},{question:"O serviço atende famílias e bagagens?",answer:"Sim. A categoria do veículo é definida conforme passageiros e bagagem; bebê conforto e cadeirinha podem ser solicitados."}],seoTitle:"Transfer Porto Seguro para Trancoso",seoDescription:"Reserve seu transfer privativo do Aeroporto de Porto Seguro para Trancoso. Motorista local, apoio com bagagens e rotas via balsa ou BR-367.",opening:"A Nativos Experiences oferece transfer privativo do Aeroporto de Porto Seguro para Trancoso, na Bahia, com motorista local e apoio desde o desembarque.",relatedSlugs:["transfer-aeroporto","transfer-blindado","motorista-a-disposicao"]},
	 transfer:{type:"transfer",slug:"transfer-trancoso",aliases:[],kicker:"TRANSFER · TRANCOSO E REGIÃO",title:"O caminho até o destino também pode ser leve.",intro:"Transfers privativos entre aeroportos, pousadas, villas, praias e cidades da Costa do Descobrimento.",image:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/gltiRcInjrrrCZrE.webp",imageAlt:"Estrada costeira entre Trancoso e destinos da Bahia",heading:"Você escolhe o lugar.\nA gente conhece o caminho.",body:"De Trancoso a Arraial d’Ajuda, Praia do Espelho, Caraíva, Santo André, Corumbau ou Itacaré. Também cuidamos dos deslocamentos internos: pousada, Quadrado, restaurante, praia ou festa.",items:["Trancoso · Arraial d’Ajuda","Trancoso · Praia do Espelho","Trancoso · Caraíva","Rotas especiais sob consulta"],cta:"Planejar meu trajeto",faqs:[...commonFaqs,{question:"Vocês fazem transfer entre cidades?",answer:"Sim. Organizamos trajetos privativos entre Trancoso, aeroportos, vilas, praias e outros destinos da Bahia sob consulta."}]},
 	 tours:{type:"tours",slug:"passeios",aliases:[],kicker:"PASSEIOS · BAHIA",title:"Passeios privativos para viver a Costa do Descobrimento com tempo.",intro:"Saia da sua hospedagem, escolha o destino e aproveite o dia sem se preocupar com a volta. O motorista aguarda durante o passeio e retorna com você no mesmo veículo.",image:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/KIZKtHuAwdfwuLtz.webp",imageAlt:"Praia da Costa do Descobrimento para um passeio privativo saindo de Trancoso",heading:"Você escolhe o destino.\nA gente cuida do dia.",body:"Os passeios têm duração de até 8 horas e saem diretamente da sua hospedagem. O veículo leva você até Arraial d’Ajuda, Praia do Espelho, Caraíva ou Porto Seguro; o motorista aguarda no local durante todo o tempo combinado e, ao final, leva você de volta para a hospedagem no mesmo veículo. As rotas acima são as mais solicitadas — se você quiser outro trajeto, montamos uma opção personalizada sob consulta.\n\nTodos os passeios são 100% privativos. Você viaja apenas com o seu grupo, com liberdade para aproveitar cada parada no seu ritmo.",items:["Até 8 horas de duração","Saída direto da sua hospedagem","Motorista aguarda durante todo o passeio","Retorno à hospedagem no mesmo veículo","Arraial d’Ajuda, Praia do Espelho, Caraíva ou Porto Seguro","Rotas personalizadas sob consulta"],cta:"Planejar meu passeio",faqs:[{question:"Como funciona um passeio privativo?",answer:"O motorista busca você diretamente na hospedagem, leva até o destino escolhido, aguarda no local durante todo o passeio e retorna com você para a hospedagem no mesmo veículo."},{question:"O motorista fica esperando durante o passeio?",answer:"Sim. O motorista permanece aguardando no local durante o tempo combinado, em passeios de até 8 horas."},{question:"Quais destinos posso conhecer saindo de Trancoso?",answer:"As opções mais solicitadas são Arraial d’Ajuda, Praia do Espelho, Caraíva e Porto Seguro. Outras rotas podem ser montadas sob consulta."},{question:"O passeio é compartilhado com outros passageiros?",answer:"Não. Todos os passeios são 100% privativos para o seu grupo."}],seoTitle:"Passeios Privativos saindo de Trancoso",seoDescription:"Passeios privativos de até 8 horas saindo da sua hospedagem em Trancoso para Arraial d’Ajuda, Praia do Espelho, Caraíva ou Porto Seguro, com motorista aguardando.",opening:"Os passeios da Nativos Experiences saem da sua hospedagem em Trancoso, levam você ao destino escolhido e incluem motorista aguardando durante todo o passeio, com retorno no mesmo veículo.",relatedSlugs:["destinos","motorista-a-disposicao","transfer-trancoso"]},
	 fleet:{type:"fleet",slug:"frota",aliases:[],kicker:"FROTA · CONFORTO",title:"O carro certo para o jeito que você viaja.",intro:"Dez categorias para diferentes grupos, bagagens e níveis de conforto — sempre com motorista local.",image:img.fleetOriginal,imageAlt:"GWM Wey 07 real da frota Nativos Experiences em área arborizada",heading:"Conforto não é excesso.\nÉ poder relaxar.",body:"A categoria é garantida; o modelo de referência pode variar conforme disponibilidade. Consideramos passageiros, bagagem, trajeto e o nível de conforto esperado.",items:["Convencional · Jeep Renegade ou similar · 4 pax","Executiva · Jeep Compass ou similar · 4 pax","Grupo · Chevrolet Spin ou similar · 6 pax","Luxo híbrida · GWM Haval H6 HEV ou similar · 4 pax","Premium · CAOA Chery Tiggo 8 Pro / Jeep Commander · 6 pax","Elite · Toyota SW4 / GWM H9 · 6 pax","Exclusive · BMW iX1 100% elétrica · 4 pax","Van Executiva · Mercedes-Benz Sprinter · até 15 pax","Van Longa · Mercedes-Benz Sprinter Longa · até 19 pax","Blindado · Mercedes-Benz GLE 400d · 6 pax"],cta:"Consultar categoria",faqs:[{question:"A Nativos garante o modelo exato do carro?",answer:"A categoria reservada é considerada na operação. O modelo de referência pode variar conforme disponibilidade e é confirmado antes do serviço."},{question:"Qual veículo atende grupos maiores?",answer:"A Van Executiva atende até 15 passageiros e a Van Longa, até 19 passageiros, conforme configuração e bagagem."},{question:"O blindado faz parte da frota?",answer:"Sim. O Mercedes-Benz GLE 400d blindado está disponível sob demanda, com reserva antecipada recomendada."}]},
 armored:{type:"armored",slug:"transfer-blindado",aliases:["transfer-blindado-trancoso"],kicker:"TRANSFER · BLINDADO",title:"Segurança reforçada, sem abrir mão da discrição.",intro:"O Mercedes-Benz GLE 400d blindado está disponível sob demanda para quem precisa de uma camada adicional de proteção em Trancoso e região.",image:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/nyqshkhBcWrZDrcj.png",imageAlt:"Mercedes-Benz GLE 400d blindado em trajeto na Bahia",heading:"Proteção para seguir\ncom tranquilidade.",body:"Executivos, famílias, artistas, autoridades e eventos podem solicitar o veículo blindado com antecedência. A operação permanece discreta do primeiro embarque ao último retorno.",items:["Mercedes-Benz GLE 400d","Até 6 passageiros","Disponível sob demanda","Reserva antecipada recomendada"],cta:"Solicitar transfer blindado",faqs:[{question:"O blindado precisa de reserva com quanto tempo de antecedência?",answer:"Recomendamos solicitar com antecedência para confirmar a disponibilidade do Mercedes-Benz GLE 400d e organizar a operação com discrição."},{question:"O blindado atende aeroporto e eventos?",answer:"Sim. Pode ser solicitado para transfers de aeroporto, deslocamentos durante a estadia, casamentos e eventos, sempre sob consulta."},{question:"A Nativos é a única empresa da região com esse serviço?",answer:"A Nativos informa que é a única empresa da região a disponibilizar esse serviço. A disponibilidade deve ser confirmada para cada data."}]},
 chauffeur:{type:"chauffeur",slug:"motorista-a-disposicao",aliases:[],kicker:"MOTORISTA À DISPOSIÇÃO",title:"Seu dia, no seu ritmo.",intro:"Um motorista particular e um veículo dedicado para você circular sem depender de horários ou negociar cada trajeto.",image:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/hodWAOaJoddYhWeW.webp",imageAlt:"Motorista local aguardando passageiros em hospedagem de Trancoso",heading:"Mais tempo para viver.\nMenos tempo organizando.",body:"Escolha o período que faz sentido para a sua estadia: 4h, 8h, 12h ou 24h. O motorista leva, aguarda e retorna quando você decidir.",items:["Períodos de 4h, 8h, 12h ou 24h","Veículo 100% dedicado","Motorista local e discreto","Ideal para praias, restaurantes e eventos"],cta:"Consultar motorista à disposição",faqs:[...commonFaqs,{question:"O motorista fica disponível durante todo o período contratado?",answer:"Sim. O veículo e o motorista ficam dedicados ao seu grupo durante o período escolhido, dentro do roteiro combinado."}]},
 concierge:{type:"concierge",slug:"concierge-trancoso",aliases:["concierge"],kicker:"CONCIERGE · TRANCOSO",title:"Para viver Trancoso sem perder tempo procurando.",intro:"Restaurantes, praias, barcos, villas e experiências escolhidas para os seus dias — com um concierge que conhece a região por dentro.",image:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/allohvlHTfuVZZST.webp",imageAlt:"Praia e paisagem da Costa do Descobrimento para planejar experiências em Trancoso",heading:"O que você quiser viver.\nA gente ajuda a acontecer.",body:"Do jantar na villa ao passeio de barco, do chef particular à massagem depois da praia. O concierge Nativos coordena os detalhes da sua estadia com olhar local e uma conversa direta pelo WhatsApp.",items:["Restaurantes e beach clubs","Barcos, praias e passeios privativos","Chef, compras e serviços para a villa","Bem-estar, beleza e experiências"],cta:"Falar com concierge",faqs:[...commonFaqs,{question:"O concierge também organiza reservas?",answer:"Sim. Conte o que deseja viver em Trancoso e o concierge orienta e coordena as possibilidades disponíveis para a sua estadia."}]},
 events:{type:"events",slug:"casamentos-e-eventos",aliases:[],kicker:"CASAMENTOS E EVENTOS",title:"A celebração merece uma chegada à altura.",intro:"Transporte de convidados, noivos, artistas e staff para casamentos, festas privadas e eventos em Trancoso e região.",image:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/ECIeMSBmbsoSAhwF.webp",imageAlt:"Veículo premium preparado para transporte de convidados em evento na Bahia",heading:"O seu evento acontece.\nA logística fica com a gente.",body:"Coordenamos vans, SUVs, veículos especiais e horários escalonados para que cada convidado saiba onde embarcar e chegue no tempo certo.",items:["Casamentos íntimos e grandes celebrações","Transporte de convidados e padrinhos","Artistas, staff, fornecedores e equipamentos","Vans, apoio e blindado sob consulta"],cta:"Solicitar orçamento de evento",faqs:[...commonFaqs,{question:"A Nativos atende casamentos em Trancoso?",answer:"Sim. Organizamos o transporte de convidados, noivos, padrinhos, artistas e equipes para casamentos e festas privadas."},{question:"É possível organizar horários diferentes para os convidados?",answer:"Sim. Trabalhamos com horários escalonados e pontos de embarque previamente combinados para facilitar a logística do evento."}]},
 destinations:{type:"destinations",slug:"destinos",aliases:[],kicker:"DESTINOS · BAHIA",title:"Trancoso é o ponto de partida.",intro:"Praias, vilas e caminhos da Costa do Descobrimento para descobrir com um motorista que sabe quando ir — e por onde.",image:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/tqJLnuypRYdQzANN.webp",imageAlt:"Praia na Costa do Descobrimento próxima a Trancoso",heading:"A Bahia tem muitos ritmos.\nEscolha o seu.",body:"Faça um passeio de dia inteiro, combine uma praia com um almoço ou crie uma rota entre destinos. Itacaré é para quem quer estender a viagem além da Costa do Descobrimento, não um bate-volta de Trancoso.",items:["Trancoso · Quadrado, praias e villas","Arraial d’Ajuda · história e mirantes","Praia do Espelho · praia e almoço","Caraíva, Santo André e Corumbau","Itacaré · extensão da viagem pela Bahia"],cta:"Escolher meu destino",faqs:[...commonFaqs,{question:"Itacaré é perto de Trancoso?",answer:"Não é um bate-volta próximo. Itacaré fica em outra região da Bahia e faz sentido para quem deseja estender a viagem além da Costa do Descobrimento."}]},
 about:{type:"about",slug:"sobre-nativos",aliases:["sobre"],kicker:"SOBRE · NATIVOS EXPERIENCES",title:"Nascemos em Trancoso para fazer você se sentir em casa.",intro:"Desde 2015, cuidamos de chegadas, deslocamentos e detalhes de estadias com discrição, pontualidade e conhecimento local.",image:img.arrival,imageAlt:"Chegada acolhedora de viajantes em hospedagem de Trancoso",heading:"Conhecer o destino\né cuidar melhor.",body:"A Nativos nasceu levando amigos do aeroporto ao Quadrado. Hoje, uma equipe local atende famílias, viajantes, executivos e eventos que valorizam a tranquilidade de ter alguém de confiança no caminho.",items:["Atendimento privativo, um cliente por vez","Motoristas locais e discretos","Curadoria de quem vive em Trancoso","Suporte pessoal pelo WhatsApp"],cta:"Conversar com a Nativos",faqs:[...commonFaqs,{question:"Onde a Nativos Experiences está situada?",answer:"A Nativos Experiences está situada em Trancoso, Bahia, com atendimento local para transfers e serviços de hospitalidade na região."}]},
 booking:{type:"booking",slug:"reserva-online",aliases:["reserva"],kicker:"RESERVA · NATIVOS EXPERIENCES",title:"Sua chegada começa com uma conversa.",intro:"Envie o voo, a hospedagem e o que você precisa. Um concierge confirma veículo, motorista, disponibilidade e valor.",image:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/gsTpXZOkVNducwum.webp",imageAlt:"Detalhe de conforto no interior de veículo para reserva em Trancoso",heading:"Você informa os detalhes.\nA gente cuida do caminho.",body:"Para solicitar um transfer, conte a origem, o destino, a data, o horário, o número de passageiros e a bagagem. Se houver voo, envie o número para acompanharmos a chegada.",items:["Transfer de aeroporto ou entre cidades","Motorista à disposição","Concierge e experiências","Eventos e casamentos"],cta:"Abrir reserva no WhatsApp",faqs:[...commonFaqs,{question:"Quais informações devo enviar para reservar?",answer:"Informe origem, destino, data, horário, passageiros, bagagem, hospedagem e o número do voo, se houver."}]},
	 partnerships:{type:"partnerships",slug:"parcerias",aliases:[],kicker:"PARCERIAS · NATIVOS EXPERIENCES",title:"Uma operação local para cuidar dos seus hóspedes.",intro:"Transfer, motorista e concierge para hotéis, pousadas, villas, imobiliárias, agências, DMCs, cerimonialistas e produtoras de evento.",image:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/oeIYXQIDdmsezNou.webp",imageMobile:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/CSAFLzWlbPbtvXRM.webp",imageAlt:"Entrada do Hotel Fasano preparada para atender hóspedes e parceiros em Trancoso",heading:"Você cuida da experiência.\nA gente sustenta o caminho.",body:"A Nativos apoia parceiros que precisam de uma operação recorrente, comunicação organizada e atendimento próximo em Trancoso e região. O escopo pode incluir transfers, motoristas à disposição, eventos, casamentos e concierge. O comissionamento e o formato de trabalho são alinhados caso a caso, sem tabela pública.",items:["Hotéis, pousadas e villas","Imobiliárias, agências e DMCs","Cerimonialistas e produtoras de eventos","Ponto de contato dedicado","Operação recorrente sob alinhamento"],cta:"Falar sobre parceria",faqs:[{question:"Com quais parceiros a Nativos trabalha?",answer:"Atendemos hotéis, pousadas, villas, imobiliárias, agências de viagem, DMCs, cerimonialistas e produtoras de eventos."},{question:"Existe comissionamento para parceiros?",answer:"O formato comercial é alinhado caso a caso, conforme o escopo e a recorrência da operação. Não trabalhamos com números públicos nesta página."},{question:"Como começo uma parceria?",answer:"Envie pelo WhatsApp o nome da empresa, o tipo de operação e o volume aproximado de atendimento. Um ponto de contato retorna para conversar."}]}
};

/* Casa de Areia — fonte única do enquadramento dos heroes. Novas fotos herdam assunto à direita e preservação integral no mobile. */
const serviceImagePresentation: Record<ServiceType, ImagePresentation> = {
  airport: { imageFocus: "72% center", imageFocusMobile: "right center", imageFit: "cover", imageFitMobile: "contain" },
  portoSeguro: { imageFocus: "74% center", imageFocusMobile: "right center", imageFit: "cover", imageFitMobile: "contain" },
  transfer: { imageFocus: "72% center", imageFocusMobile: "right center", imageFit: "cover", imageFitMobile: "contain" },
  tours: { imageFocus: "70% center", imageFocusMobile: "right center", imageFit: "cover", imageFitMobile: "contain" },
  fleet: { imageFocus: "74% center", imageFocusMobile: "right center", imageFit: "cover", imageFitMobile: "contain" },
  armored: { imageFocus: "78% center", imageFocusMobile: "right center", imageFit: "cover", imageFitMobile: "contain" },
  chauffeur: { imageFocus: "78% center", imageFocusMobile: "right center", imageFit: "cover", imageFitMobile: "contain" },
  concierge: { imageFocus: "72% center", imageFocusMobile: "right center", imageFit: "cover", imageFitMobile: "contain" },
  events: { imageFocus: "78% center", imageFocusMobile: "right center", imageFit: "cover", imageFitMobile: "contain" },
  destinations: { imageFocus: "70% center", imageFocusMobile: "right center", imageFit: "cover", imageFitMobile: "contain" },
  about: { imageFocus: "right center", imageFocusMobile: "right center", imageFit: "cover", imageFitMobile: "contain" },
  booking: { imageFocus: "74% center", imageFocusMobile: "right center", imageFit: "cover", imageFitMobile: "contain" },
  partnerships: { imageFocus: "80% center", imageFocusMobile: "right center", imageFit: "cover", imageFitMobile: "cover" },
};
const pageOverrides: Partial<Record<ServiceType, Partial<ServiceData>>> = {
  armored: {
    title:"Transfer blindado em Porto Seguro e Trancoso, com discrição.",
    intro:"A Nativos Experiences opera o único veículo blindado disponível para transfer executivo na região de Porto Seguro e Trancoso: um Mercedes-Benz GLE 400d blindado.",
    opening:"A Nativos Experiences opera o único veículo blindado disponível para transfer executivo na região de Porto Seguro e Trancoso: um Mercedes-Benz GLE 400d blindado.",
    body:"O serviço foi pensado para executivos, autoridades, artistas, famílias que buscam discrição e eventos de alto perfil. A reserva é feita com antecedência recomendada, definição da região atendida e alinhamento do ponto de embarque, horário e rota. O motorista conduz a operação com discrição do aeroporto ao hotel, entre compromissos ou durante um evento.",
    items:["Mercedes-Benz GLE 400d blindado","Único blindado do segmento na região","Transfer de aeroporto, hotel e eventos","Motorista discreto e operação sob demanda","Reserva antecipada recomendada"],
    cta:"Solicitar transfer blindado",
    seoTitle:"Transfer Blindado Porto Seguro e Trancoso",
    seoDescription:"Transfer blindado em Porto Seguro e Trancoso com Mercedes-Benz GLE 400d. Serviço sob demanda para executivos, famílias, autoridades, artistas e eventos.",
    relatedSlugs:["casamentos-e-eventos","motorista-a-disposicao","transfer-porto-seguro-trancoso"],
    faqs:[{question:"O blindado atende no aeroporto?",answer:"Sim. O Mercedes-Benz GLE 400d pode ser solicitado para chegada ou saída pelo Aeroporto de Porto Seguro, Aeroporto Terravista e outras portas de entrada atendidas sob consulta."},{question:"Qual é o nível de blindagem?",answer:"O nível de blindagem deve ser confirmado no atendimento para a configuração disponível na data solicitada."},{question:"Preciso reservar com quanto tempo de antecedência?",answer:"A reserva antecipada é recomendada para confirmar a disponibilidade do veículo e organizar a operação com discrição."},{question:"O serviço atende fora de Trancoso?",answer:"Sim. O atendimento pode contemplar Porto Seguro, Trancoso e outros pontos da Costa do Descobrimento, conforme rota e disponibilidade."}]
  },
  events: {
    opening:"A Nativos Experiences coordena transporte premium para casamentos, festas privadas, festivais e eventos em Trancoso e região, atendendo convidados, noivos, artistas, staff e fornecedores.",
    body:"Para casais e cerimonialistas, organizamos a chegada dos convidados, padrinhos e noivos com horários e pontos de embarque alinhados ao roteiro da celebração. Para produtoras e agências, executamos a logística de convidados, artistas, staff, fornecedores e equipamentos mantendo o padrão de atendimento definido pelo parceiro. A operação pode envolver vans, SUVs, veículos especiais e blindado sob consulta.",
    items:["Casamentos íntimos e grandes celebrações","Festas privadas e festivais","Convidados, noivos, artistas e staff","Cerimonialistas e wedding planners","Produtoras, agências e fornecedores","Vans, SUVs e blindado sob consulta"],
    seoTitle:"Transfer para Casamentos e Eventos em Trancoso",
    seoDescription:"Transporte premium para casamentos, festas privadas, festivais e eventos em Trancoso. Logística de convidados, noivos, artistas, staff e fornecedores.",
    relatedSlugs:["transfer-blindado","motorista-a-disposicao","concierge-trancoso"],
    faqs:[{question:"A Nativos atende casamentos em Trancoso?",answer:"Sim. Coordenamos transporte de convidados, noivos, padrinhos, artistas e equipes para casamentos e celebrações na região."},{question:"Como funciona a logística para cerimonialistas?",answer:"Alinhamos roteiro, horários, pontos de embarque e categorias de veículos para executar a operação mantendo o padrão de atendimento definido pelo evento ou parceiro."},{question:"A empresa atende produtoras e agências?",answer:"Sim. Produtoras e agências podem solicitar logística para convidados, artistas, staff, fornecedores e equipamentos, conforme escopo do evento."},{question:"É possível solicitar blindado para um evento?",answer:"Sim. O veículo blindado pode ser solicitado sob consulta, com reserva antecipada recomendada para confirmar disponibilidade."}]
  },
  chauffeur: {
    opening:"A Nativos Experiences oferece motorista particular em Trancoso, Porto Seguro e região, com veículo dedicado para quem deseja circular pela Bahia sem depender de horários ou organizar cada trajeto.",
    body:"O serviço é indicado para famílias, executivos, casais e grupos que desejam liberdade durante a estadia. O motorista busca, aguarda e retorna conforme o roteiro combinado, seja para praias, restaurantes, villas, eventos ou compromissos. Os períodos de 4h, 8h, 12h ou 24h são definidos conforme a necessidade e a disponibilidade.",
    seoTitle:"Motorista Particular em Trancoso e Porto Seguro",
    seoDescription:"Motorista particular em Trancoso e Porto Seguro com veículo dedicado. Reserve por 4h, 8h, 12h ou 24h para praias, restaurantes, eventos e passeios.",
    relatedSlugs:["transfer-porto-seguro-trancoso","concierge-trancoso","casamentos-e-eventos"]
  }
};
const seoEnhancements: Partial<Record<ServiceType, Partial<ServiceData>>> = {
  airport: { seoTitle:"Transfer do Aeroporto de Porto Seguro para Trancoso", seoDescription:"Reserve transfer privativo do Aeroporto de Porto Seguro, Terravista ou Outeiro das Brisas para Trancoso, com motorista local e apoio desde o desembarque.", opening:"A Nativos Experiences organiza o transfer do Aeroporto de Porto Seguro para Trancoso, além das chegadas pelo Terravista e Outeiro das Brisas, com motorista local, monitoramento de voo e apoio com bagagens.", relatedSlugs:["transfer-porto-seguro-trancoso","frota","reserva-online"], faqs:[{question:"A Nativos faz transfer do Aeroporto de Porto Seguro para Trancoso?",answer:"Sim. Organizamos transfer privativo entre o Aeroporto de Porto Seguro e Trancoso, com opção de rota via balsa ou BR-367 e atendimento conforme o horário do voo."},{question:"O transfer atende o Aeroporto Terravista?",answer:"Sim. O Terravista fica a aproximadamente 15 minutos de Trancoso e pode ser incluído na reserva sem travessia de balsa."},{question:"O motorista espera em caso de atraso do voo?",answer:"Envie o número do voo no atendimento. Assim, a equipe consegue organizar a operação conforme a previsão de chegada e orientar o ponto de encontro."}] },
  tours: { seoTitle:"Passeios Privativos saindo de Trancoso", seoDescription:"Passeios privativos de até 8 horas saindo da hospedagem em Trancoso para Arraial d’Ajuda, Praia do Espelho, Caraíva ou Porto Seguro, com motorista aguardando.", opening:"Os passeios da Nativos Experiences saem da sua hospedagem em Trancoso, levam você ao destino escolhido e incluem motorista aguardando durante todo o passeio, com retorno no mesmo veículo.", relatedSlugs:["destinos","motorista-a-disposicao","transfer-trancoso"], faqs:[{question:"Como funciona um passeio privativo?",answer:"O motorista busca você diretamente na hospedagem, leva até o destino escolhido, aguarda no local durante todo o passeio e retorna com você para a hospedagem no mesmo veículo."},{question:"O motorista fica esperando durante o passeio?",answer:"Sim. O motorista permanece aguardando no local durante o tempo combinado, em passeios de até 8 horas."},{question:"Quais destinos posso conhecer saindo de Trancoso?",answer:"As opções mais solicitadas são Arraial d’Ajuda, Praia do Espelho, Caraíva e Porto Seguro. Outras rotas podem ser montadas sob consulta."}] },
  transfer: { seoTitle:"Transfer Privativo em Trancoso e na Costa do Descobrimento", seoDescription:"Transfer privativo em Trancoso, Porto Seguro e Costa do Descobrimento para aeroportos, praias, pousadas, villas, restaurantes e destinos da Bahia.", opening:"Para quem procura transfer em Trancoso, a Nativos Experiences combina motorista local, veículo adequado e planejamento do trajeto entre aeroporto, hospedagem, praia, restaurante e outros destinos da Costa do Descobrimento.", relatedSlugs:["transfer-aeroporto","transfer-porto-seguro-trancoso","destinos"], faqs:[{question:"Vocês fazem transfer privativo em Trancoso?",answer:"Sim. Atendemos deslocamentos entre aeroportos, pousadas, villas, praias, restaurantes, eventos e cidades da Costa do Descobrimento."},{question:"Quais rotas podem ser feitas a partir de Trancoso?",answer:"As rotas incluem Porto Seguro, Arraial d’Ajuda, Praia do Espelho, Caraíva, Santo André, Corumbau e outros trajetos sob consulta."},{question:"O serviço é exclusivo para um grupo?",answer:"Sim. O transfer é privativo e a categoria do veículo é definida de acordo com passageiros, bagagem, trajeto e conforto esperado."}] },
  fleet: { seoTitle:"Frota de Carros para Transfer de Luxo em Trancoso", seoDescription:"Conheça a frota da Nativos Experiences para transfer em Trancoso: SUVs, vans, veículos premium, híbridos, elétricos e Mercedes-Benz GLE 400d blindado.", opening:"A frota para transfer de luxo em Trancoso reúne dez categorias de veículos para diferentes grupos, bagagens e momentos da estadia, sempre com motorista local.", relatedSlugs:["transfer-blindado","transfer-aeroporto","reserva-online"], faqs:[{question:"Quantas categorias de veículos a Nativos oferece?",answer:"A frota é organizada em dez categorias, incluindo veículos convencionais, executivos, premium, SUVs, vans e o Mercedes-Benz GLE 400d blindado."},{question:"Qual veículo atende até 19 passageiros?",answer:"A Van Longa, baseada na Mercedes-Benz Sprinter Longa, atende até 19 passageiros conforme configuração e volume de bagagem."},{question:"Como escolher o veículo para o transfer?",answer:"A equipe considera número de passageiros, bagagem, trajeto e nível de conforto para indicar a categoria mais adequada."}] },
  concierge: { seoTitle:"Concierge em Trancoso para Experiências e Reservas", seoDescription:"Concierge local em Trancoso para restaurantes, beach clubs, praias, barcos, villas, chef particular, bem-estar e experiências na Bahia.", opening:"O concierge da Nativos Experiences ajuda a organizar os detalhes da sua estadia em Trancoso, com curadoria local para restaurantes, praias, barcos, villas, bem-estar e experiências especiais.", relatedSlugs:["transfer-trancoso","destinos","motorista-a-disposicao"], faqs:[{question:"O concierge da Nativos faz reservas em Trancoso?",answer:"Sim. A equipe orienta e coordena possibilidades de restaurantes, beach clubs, passeios, barcos, serviços para villa e outras experiências disponíveis."},{question:"O concierge atende hóspedes em villas?",answer:"Sim. O atendimento pode incluir chef particular, compras, serviços para a villa, bem-estar e deslocamentos durante a estadia."},{question:"Como solicitar uma experiência em Trancoso?",answer:"Envie uma mensagem pelo WhatsApp com a data, o número de pessoas e o que você deseja viver. O concierge retorna com as possibilidades."}] },
  destinations: { seoTitle:"Destinos e Rotas Privativas a Partir de Trancoso", seoDescription:"Planeje rotas privativas de Trancoso para Arraial d’Ajuda, Praia do Espelho, Caraíva, Santo André, Corumbau e Itacaré com motorista local.", opening:"A Nativos Experiences organiza deslocamentos privativos a partir de Trancoso para praias, vilas e destinos da Bahia, respeitando o tempo de viagem e o ritmo da sua estadia.", relatedSlugs:["transfer-trancoso","transfer-porto-seguro-trancoso","concierge-trancoso"], faqs:[{question:"Quais destinos posso visitar saindo de Trancoso?",answer:"É possível organizar trajetos para Arraial d’Ajuda, Praia do Espelho, Caraíva, Santo André, Corumbau, Itacaré e outros destinos sob consulta."},{question:"A Nativos faz transfer de Trancoso para Caraíva?",answer:"Sim. A rota pode ser organizada de forma privativa, com alinhamento de horário, ponto de embarque, bagagem e condições do caminho."},{question:"Itacaré pode ser feita em um bate-volta?",answer:"Itacaré é uma extensão da viagem para além da Costa do Descobrimento, e não um bate-volta próximo a Trancoso."}] },
  about: { seoTitle:"Nativos Experiences: Transfer e Concierge em Trancoso", seoDescription:"Conheça a Nativos Experiences, empresa local de transfer privativo e concierge em Trancoso, Bahia, com operação desde 2015.", opening:"Desde 2015, a Nativos Experiences atende quem chega a Trancoso e circula pela Bahia com transfer privativo, motorista local, concierge e cuidado nos detalhes.", relatedSlugs:["transfer-aeroporto","concierge-trancoso","reserva-online"], faqs:[{question:"A Nativos Experiences fica em Trancoso?",answer:"Sim. A Nativos Experiences tem operação local em Trancoso, Bahia, e atende transfer, motorista, concierge e eventos na região."},{question:"Desde quando a Nativos atua?",answer:"A operação da Nativos Experiences começou em 2015, com foco em atendimento local, discrição e conhecimento dos caminhos da região."}] },
  booking: { seoTitle:"Reserve seu Transfer Privativo em Trancoso", seoDescription:"Reserve transfer de aeroporto, motorista à disposição, concierge ou transporte para eventos em Trancoso pelo atendimento direto da Nativos Experiences.", opening:"A reserva do seu transfer em Trancoso começa com uma conversa direta. Envie os detalhes da viagem e a equipe confirma a categoria, a disponibilidade e o valor.", relatedSlugs:["transfer-aeroporto","frota","casamentos-e-eventos"], faqs:[{question:"Como reservar um transfer em Trancoso?",answer:"Envie pelo WhatsApp a data, origem, destino, passageiros, bagagem, hospedagem e número do voo, quando houver. A equipe confirma a melhor opção."},{question:"Posso reservar um motorista à disposição?",answer:"Sim. Informe se precisa de 4h, 8h, 12h ou 24h de veículo dedicado para organizar praias, restaurantes, eventos e compromissos."},{question:"Como solicitar um orçamento para casamento?",answer:"Envie a data, local, número de convidados e o tipo de operação. A equipe organiza uma conversa específica para a logística do evento."}] },
  partnerships: { seoTitle:"Operação de Transfer para Hotéis e Eventos em Trancoso", seoDescription:"Operação local de transfer, motorista, concierge e logística de eventos para hotéis, villas, agências, DMCs e cerimonialistas em Trancoso.", opening:"A Nativos Experiences apoia hotéis, villas, agências, DMCs, cerimonialistas e produtoras com uma operação local organizada para transfer, eventos, casamentos e concierge em Trancoso.", relatedSlugs:["casamentos-e-eventos","transfer-aeroporto","frota"], faqs:[{question:"A Nativos atende hotéis e villas em Trancoso?",answer:"Sim. A operação atende hotéis, pousadas, villas, imobiliárias, agências, DMCs, cerimonialistas e produtoras de eventos."},{question:"A Nativos faz logística de casamentos?",answer:"Sim. A equipe coordena veículos, horários, pontos de embarque e deslocamentos para convidados, noivos, artistas, staff e fornecedores."},{question:"A operação pode ser feita em nome do parceiro?",answer:"O formato de operação e comunicação é alinhado caso a caso, inclusive para demandas discretas e recorrentes de parceiros."}] }
};

export const allSlugs = Object.values(serviceData).flatMap((item) => [item.slug, ...item.aliases]);
export const canonicalSlugs = Object.values(serviceData).map((item) => item.slug);
export function getServiceBySlug(slug: string) { const item = Object.values(serviceData).find((entry) => entry.slug === slug || entry.aliases.includes(slug)); return item ? { ...item, ...serviceImagePresentation[item.type], ...pageOverrides[item.type], ...seoEnhancements[item.type] } : undefined; }


export type Locale = "pt-BR" | "en";
export type LocalizedServiceData = ServiceData & { locale: Locale };

type EnglishCopy = Omit<Partial<ServiceData>, "type" | "slug" | "aliases" | "image" | "imageAlt" | "relatedSlugs"> & { imageAlt: string; seoTitle: string; seoDescription: string; faqs: Faq[]; items: string[] };

const englishCopy: Record<ServiceType, EnglishCopy> = {
  airport: { kicker:"TRANSFER · AIRPORT", title:"From the airport to Trancoso, with every detail cared for.", intro:"Private arrivals from Porto Seguro, Terravista or Outeiro das Brisas airports. You land. Nativos takes care of the rest.", imageAlt:"Private arrival service in a premium vehicle in Trancoso", heading:"Three gateways.\nOne calm arrival.", body:"We serve the region’s main airports with a local chauffeur, a dedicated vehicle and luggage assistance. From Porto Seguro Airport (BPS) to Trancoso, the journey usually takes 1h15 to 2h by ferry, or up to 1h20 via BR-367, the overland route of approximately 80 km. Terravista Airport (SBTV) is about 15 minutes from Trancoso, without a ferry crossing. Outeiro das Brisas (SNEC) is mainly used by executive or private aviation heading to Praia do Espelho and nearby destinations.", items:["Porto Seguro (BPS) — Trancoso · 1h15 to 2h by ferry","Porto Seguro (BPS) — Trancoso · up to 1h20 via BR-367","Terravista (SBTV) — Trancoso · approximately 15 minutes","Outeiro das Brisas (SNEC) · private aviation to Praia do Espelho","Flight monitoring and chauffeur waiting"], cta:"Book an airport transfer", seoTitle:"Luxury Airport Transfer to Trancoso", seoDescription:"Book a private airport transfer from Porto Seguro, Terravista or Outeiro das Brisas to Trancoso with a local chauffeur and luggage assistance.", opening:"Nativos Experiences provides private airport transfers to Trancoso, Bahia, with a local chauffeur, a dedicated vehicle and attentive support from the moment you land.", faqs:[{question:"How long does Porto Seguro to Trancoso take?",answer:"By ferry, the journey usually takes 1h15 to 2h. Via BR-367, it can take up to 1h20 over approximately 80 km, depending on road conditions."},{question:"How long is the transfer from Terravista Airport?",answer:"Terravista Airport is approximately 15 minutes from Trancoso and does not require a ferry crossing."},{question:"Does Nativos monitor flight arrivals?",answer:"You can share your flight number when booking so the operation can be coordinated around the expected arrival."}] },
  tours: { kicker:"TOURS · BAHIA", title:"Private days out from Trancoso, with time to enjoy the destination.", intro:"Leave from your accommodation, choose where you want to go and enjoy the day without worrying about the return. Your chauffeur waits during the outing and drives you back in the same vehicle.", imageAlt:"Beach on the Discovery Coast for a private day out from Trancoso", heading:"You choose the destination.\nWe take care of the day.", body:"Outings last up to 8 hours and depart directly from your accommodation. The vehicle takes you to Arraial d’Ajuda, Praia do Espelho, Caraíva or Porto Seguro; your chauffeur waits on site throughout the agreed time and drives you back to your accommodation in the same vehicle. These are the most requested routes — other itineraries can be arranged on request.\n\nEvery outing is 100% private. You travel only with your group, with the freedom to experience each stop at your own pace.", items:["Up to 8 hours","Departure from your accommodation","Chauffeur waits throughout the outing","Return to your accommodation in the same vehicle","Arraial d’Ajuda, Praia do Espelho, Caraíva or Porto Seguro","Custom routes on request"], cta:"Plan my day out", seoTitle:"Private Day Trips from Trancoso", seoDescription:"Private outings of up to 8 hours from your accommodation in Trancoso to Arraial d’Ajuda, Praia do Espelho, Caraíva or Porto Seguro, with a waiting chauffeur.", opening:"Nativos Experiences outings depart from your accommodation in Trancoso, take you to the destination of your choice and include a chauffeur waiting throughout the outing, with a return in the same vehicle.", faqs:[{question:"How does a private day out work?",answer:"Your chauffeur picks you up at your accommodation, drives you to the chosen destination, waits throughout the outing and returns you to your accommodation in the same vehicle."},{question:"Does the chauffeur wait during the outing?",answer:"Yes. The chauffeur remains waiting on site for the agreed time, on outings of up to 8 hours."},{question:"Are the outings shared with other passengers?",answer:"No. Every outing is 100% private for your group."}] },
  transfer: { kicker:"TRANSFER · TRANCOSO & REGION", title:"The journey to your destination can feel effortless.", intro:"Private transfers between airports, hotels, villas, beaches and towns along Brazil’s Discovery Coast.", imageAlt:"Coastal road between Trancoso and destinations in Bahia", heading:"You choose the place.\nWe know the way.", body:"From Trancoso to Arraial d’Ajuda, Praia do Espelho, Caraíva, Santo André, Corumbau or Itacaré. We also arrange local rides to your pousada, the Quadrado, restaurants, beaches and celebrations.", items:["Trancoso · Arraial d’Ajuda","Trancoso · Praia do Espelho","Trancoso · Caraíva","Special routes on request"], cta:"Plan my route", seoTitle:"Private Transfers in Trancoso and Bahia", seoDescription:"Private transfers between Trancoso, Porto Seguro, beaches, villas and destinations along the Discovery Coast with local support.", opening:"Nativos Experiences arranges private transfers across Trancoso and the Discovery Coast, with a local chauffeur and a route planned around your stay.", faqs:[{question:"Do you provide transfers between towns?",answer:"Yes. We arrange private journeys between Trancoso, airports, villages, beaches and other Bahia destinations on request."},{question:"Can you organize local rides in Trancoso?",answer:"Yes. We can coordinate rides to your hotel, the Quadrado, restaurants, beaches and events."}] },
  portoSeguro: { kicker:"TRANSFER · PORTO SEGURO — TRANCOSO", title:"From Porto Seguro Airport to Trancoso, with the route already taken care of.", intro:"Private transfer between Porto Seguro Airport and Trancoso, with a local chauffeur, luggage assistance and a route chosen around your schedule.", imageAlt:"Chauffeur welcoming travelers on a private transfer from Porto Seguro to Trancoso", heading:"Your gateway to\nBahia.", body:"Nativos Experiences operates private transfers between Porto Seguro Airport and Trancoso. By ferry, the journey usually takes 1h15 to 2h. Via BR-367, without the crossing, it can take up to 1h20 over approximately 80 km. The route is aligned around traffic, ferry conditions and your arrival time.", items:["Porto Seguro Airport (BPS) — Trancoso","1h15 to 2h by ferry","Up to 1h20 via BR-367","Local chauffeur and luggage assistance","Flight monitoring on request"], cta:"Book Porto Seguro — Trancoso", seoTitle:"Porto Seguro Airport to Trancoso Transfer", seoDescription:"Private transfer from Porto Seguro Airport to Trancoso with a local chauffeur, luggage assistance and ferry or road route options.", opening:"Nativos Experiences provides private transfers from Porto Seguro Airport to Trancoso, Bahia, with local knowledge and support from the moment you land.", faqs:[{question:"How long is the transfer from Porto Seguro Airport to Trancoso?",answer:"By ferry, it usually takes 1h15 to 2h. Via BR-367, it can take up to 1h20 over approximately 80 km, depending on conditions."},{question:"Can I share my flight number?",answer:"Yes. Send it when booking so the arrival operation can be organized around the expected landing time."},{question:"Which route is used?",answer:"The journey can be made by ferry or via BR-367 without the crossing. We align the best option around schedule, traffic and road conditions."}] },
  fleet: { kicker:"FLEET · COMFORT", title:"The right vehicle for the way you travel.", intro:"Ten categories for different groups, luggage and comfort expectations — always with a local chauffeur.", imageAlt:"Real GWM Wey 07 from the Nativos Experiences fleet in a landscaped setting", heading:"Comfort is not excess.\nIt is room to relax.", body:"Your reserved category is guaranteed; the reference model may vary with availability. We consider passenger count, luggage, route and the level of comfort you expect.", items:["Standard · Jeep Renegade or similar · 4 guests","Executive · Jeep Compass or similar · 4 guests","Group · Chevrolet Spin or similar · 6 guests","Luxury hybrid · GWM Haval H6 HEV or similar · 4 guests","Premium · CAOA Chery Tiggo 8 Pro / Jeep Commander · 6 guests","Elite · Toyota SW4 / GWM H9 · 6 guests","Exclusive · BMW iX1 electric · 4 guests","Executive Van · Mercedes-Benz Sprinter · up to 15 guests","Long Van · Mercedes-Benz Sprinter Long · up to 19 guests","Armored · Mercedes-Benz GLE 400d · 6 guests"], cta:"Choose a category", seoTitle:"Luxury Transfer Fleet in Trancoso", seoDescription:"Explore ten private transfer vehicle categories in Trancoso, from executive SUVs and vans to the Mercedes-Benz GLE 400d armored vehicle.", opening:"Our fleet is organized by category so your vehicle matches the group, luggage, route and comfort level of your stay.", faqs:[{question:"Is the exact vehicle model guaranteed?",answer:"The reserved category is guaranteed. The reference model may vary with availability and is confirmed before the service."},{question:"Which vehicle is best for larger groups?",answer:"The Executive Van serves up to 15 guests and the Long Van up to 19 guests, depending on configuration and luggage."},{question:"Is an armored vehicle available?",answer:"Yes. The Mercedes-Benz GLE 400d armored vehicle is available on request with advance booking recommended."}] },
  armored: { kicker:"TRANSFER · ARMORED", title:"Security without giving up comfort.", intro:"The Mercedes-Benz GLE 400d armored vehicle is available on request for guests who want an additional layer of protection in Trancoso and the region.", imageAlt:"Mercedes-Benz GLE 400d armored vehicle on a road in Bahia", heading:"Protection to move\nwith peace of mind.", body:"Executives, families, artists, authorities and events can request the armored vehicle in advance. The operation remains discreet from the first pickup to the final return.", items:["Mercedes-Benz GLE 400d","Up to 6 guests","Available on request","Advance booking recommended"], cta:"Request an armored transfer", seoTitle:"Armored Transfer in Porto Seguro and Trancoso", seoDescription:"Armored transfer in Porto Seguro and Trancoso with a Mercedes-Benz GLE 400d. On-request service for executives, families, artists, authorities and events.", opening:"Nativos Experiences operates the region’s only armored vehicle available for executive transfers between Porto Seguro and Trancoso: a Mercedes-Benz GLE 400d.", faqs:[{question:"Does the armored vehicle serve airport arrivals?",answer:"Yes. It can be requested for arrivals and departures through Porto Seguro Airport, Terravista Airport and other supported gateways."},{question:"How far in advance should I book?",answer:"Advance booking is recommended to confirm vehicle availability and organize the operation discreetly."},{question:"Does it serve events?",answer:"Yes. The armored vehicle may be requested for airport transfers, hotel movements, weddings and events, subject to availability."}] },
  chauffeur: { kicker:"PRIVATE CHAUFFEUR", title:"Your day, at your own pace.", intro:"A private chauffeur and a dedicated vehicle so you can move freely without negotiating every ride or schedule.", imageAlt:"Local chauffeur waiting for guests at a Trancoso accommodation", heading:"More time to live.\nLess time organizing.", body:"Choose the period that fits your stay: 4h, 8h, 12h or 24h. Your chauffeur takes you, waits and returns whenever you decide.", items:["4h, 8h, 12h or 24h periods","100% dedicated vehicle","Local and discreet chauffeur","Ideal for beaches, restaurants and events"], cta:"Ask about a private chauffeur", seoTitle:"Private Chauffeur in Trancoso and Porto Seguro", seoDescription:"Private chauffeur in Trancoso and Porto Seguro with a dedicated vehicle. Book for 4h, 8h, 12h or 24h for beaches, restaurants, events and days out.", opening:"Nativos Experiences offers private chauffeur service in Trancoso, Porto Seguro and the region, with a dedicated vehicle for a more fluid stay.", faqs:[{question:"Is the chauffeur dedicated for the whole booked period?",answer:"Yes. The vehicle and chauffeur remain dedicated to your group during the selected period and agreed itinerary."},{question:"Can the service be used for restaurants and beaches?",answer:"Yes. It is designed for beaches, restaurants, villas, events and flexible days around Trancoso."}] },
  concierge: { kicker:"CONCIERGE · TRANCOSO", title:"Experience Trancoso without losing time searching.", intro:"Restaurants, beaches, boats, villas and experiences selected for your days — with a concierge who knows the region from the inside.", imageAlt:"Beach and landscape on the Discovery Coast for planning Trancoso experiences", heading:"Whatever you want to experience.\nWe help make it happen.", body:"From dinner at your villa to a private boat, a personal chef or a massage after the beach. Nativos coordinates the details of your stay with local perspective and a direct WhatsApp conversation.", items:["Restaurants and beach clubs","Boats, beaches and private outings","Chef, shopping and villa services","Wellness, beauty and local experiences"], cta:"Talk to a concierge", seoTitle:"Luxury Concierge in Trancoso, Bahia", seoDescription:"Local concierge service in Trancoso for restaurants, beaches, boats, villas, wellness, chefs and private experiences.", opening:"Our Trancoso concierge brings local knowledge to the details that make a stay feel effortless, from a table at dinner to a private day on the coast.", faqs:[{question:"Can the concierge arrange reservations?",answer:"Yes. Tell us what you would like to experience in Trancoso and the concierge will guide and coordinate available options."},{question:"Does the service cover villas and private experiences?",answer:"Yes. We can assist with villa services, chefs, boats, wellness and other experiences on request."}] },
  events: { kicker:"WEDDINGS & EVENTS", title:"The celebration deserves an arrival to match.", intro:"Premium transportation for guests, couples, artists and staff at weddings, private parties and events in Trancoso and the region.", imageAlt:"Premium vehicle prepared for guests at an event in Bahia", heading:"Your event unfolds.\nWe handle the logistics.", body:"We coordinate vans, SUVs, special vehicles and staggered schedules so every guest knows where to board and arrives at the right time.", items:["Intimate weddings and large celebrations","Guest and wedding-party transportation","Artists, staff and suppliers","Wedding planners and coordinators","Producers, agencies and suppliers","Vans, SUVs and armored vehicle on request"], cta:"Plan event transportation", seoTitle:"Wedding and Event Transportation in Trancoso", seoDescription:"Premium wedding and event transportation in Trancoso for guests, couples, artists, staff, suppliers and production teams.", opening:"Nativos Experiences coordinates premium transportation for weddings, private parties, festivals and events in Trancoso and nearby destinations.", faqs:[{question:"Do you provide transportation for weddings in Trancoso?",answer:"Yes. We coordinate transportation for guests, couples, wedding parties, artists and teams across the region."},{question:"How does event logistics work?",answer:"We align the itinerary, times, boarding points and vehicle categories so the operation supports the event experience."},{question:"Can an armored vehicle be requested for an event?",answer:"Yes. It can be requested subject to availability, with advance booking recommended."}] },
  destinations: { kicker:"DESTINATIONS · BAHIA", title:"The coast reveals itself in the details of the route.", intro:"Private journeys from Trancoso to beaches, villages and destinations along the Discovery Coast.", imageAlt:"Quiet beach on the Discovery Coast in Bahia", heading:"Trancoso is the base.\nBahia is the invitation.", body:"Beyond the Quadrado are beaches, villages and roads that deserve time. Extend your journey to Itacaré when you want more of Bahia, rather than treating it as a day trip from Trancoso. Tell us where you want to go and we will shape the right way to get there.", items:["Trancoso","Arraial d’Ajuda","Praia do Espelho","Caraíva","Santo André","Corumbau","Itacaré"], cta:"Plan my destination", seoTitle:"Private Transfers from Trancoso to Bahia Destinations", seoDescription:"Private transfers from Trancoso to Arraial d’Ajuda, Praia do Espelho, Caraíva, Santo André, Corumbau and Itacaré.", opening:"From Trancoso, Nativos helps you reach the coast’s most memorable destinations with time, comfort and local perspective.", faqs:[{question:"Which destinations can you reach from Trancoso?",answer:"We serve Arraial d’Ajuda, Praia do Espelho, Caraíva, Santo André, Corumbau, Itacaré and other routes on request."},{question:"Is Itacaré suitable as a day trip?",answer:"Itacaré is better understood as an extension of the journey, not a rushed day trip from Trancoso."}] },
  about: { kicker:"THE NATIVOS WAY OF WELCOMING", title:"Knowing the destination means\nknowing how to care.", intro:"A local operation guided by proximity, discretion and attention to detail.", imageAlt:"Local road and landscape around Trancoso, Bahia", heading:"Local knowledge.\nQuiet precision.", body:"Nativos Experiences was created in Trancoso to make private travel through Bahia feel considered from the first message to the final drop-off.", items:["Local operation since 2015","Private transfers and concierge","Discreet, attentive service","Trancoso and the Discovery Coast"], cta:"Speak with our team", seoTitle:"About Nativos Experiences in Trancoso", seoDescription:"Learn about Nativos Experiences, a local luxury transfer and concierge service in Trancoso, Bahia, operating since 2015.", opening:"Nativos Experiences combines local knowledge with a discreet, attentive way of receiving guests in Trancoso and the Discovery Coast.", faqs:[{question:"Where does Nativos Experiences operate?",answer:"We are based in Trancoso and serve Porto Seguro, the Discovery Coast and selected Bahia destinations on request."}] },
  booking: { kicker:"BEFORE YOU BOARD", title:"Your reservation begins\nwith a conversation.", intro:"Tell us what you need and leave the route planning to our team.", imageAlt:"Premium vehicle waiting for a private transfer in Trancoso", heading:"A simple message.\nA well-planned arrival.", body:"Send your date, origin, destination, passenger count, luggage and flight number when applicable. A concierge confirms availability, category and value.", items:["Date and time","Origin and destination","Passengers and luggage","Flight number, if applicable"], cta:"Start a reservation", seoTitle:"Book a Private Transfer in Trancoso", seoDescription:"Book a private transfer, chauffeur or concierge service in Trancoso and Porto Seguro through the Nativos Experiences team.", opening:"Booking is direct: send the essential details by WhatsApp and a Nativos concierge will organize the best option for your stay.", faqs:[{question:"What information is needed to book?",answer:"Send the date, origin, destination, passengers, luggage and flight number when applicable. We then confirm availability, category and value."},{question:"Can I request a child seat?",answer:"Yes. Baby seat, child seat and booster seat are available at no additional cost when requested during booking."}] },
  partnerships: { kicker:"PARTNERS · LOCAL OPERATIONS", title:"Reliability that protects\nyour guest experience.", intro:"A discreet local operation for hotels, villas, agencies, wedding planners and travel professionals working in Trancoso and Bahia.", imageAlt:"Premium vehicle ready for a partner operation in Trancoso", heading:"Your guests are in good hands.\nYour operation stays clear.", body:"We execute private transfers, event movements and on-demand support with the organization and consistency expected by hospitality partners. The guest experience remains at the center of every detail.", items:["White-label transfer operations","Local chauffeurs and dedicated vehicles","Wedding and event logistics","Direct operational communication"], cta:"Discuss a partnership", seoTitle:"Luxury Transfer Operations for Partners in Trancoso", seoDescription:"Reliable white-label transfer and event logistics for hotels, villas, agencies and travel professionals in Trancoso and Bahia.", opening:"Nativos Experiences supports hospitality and travel professionals with a reliable local operation, discreet chauffeurs and clear communication from booking to completion.", faqs:[{question:"Which partners does Nativos support?",answer:"We work with hotels, villas, agencies, wedding planners, producers and travel professionals who need local transfer operations."},{question:"Can the operation be white-label?",answer:"Yes. We can work discreetly behind your brand while maintaining clear operational communication with your team."}] }
};

export const englishDifferentiators: Differentiator[] = [{kind:"water",label:"Mineral water and coconut water",text:"Mineral water and coconut water on board."},{kind:"snacks",label:"Snacks on board",text:"Curated snacks for the journey."},{kind:"sanitizer",label:"Hand sanitizer and wipes",text:"Hand sanitizer and wet wipes available on board."},{kind:"signal",label:"Starlink Internet",text:"Satellite connection on compatible vehicles and routes."},{kind:"chargers",label:"Chargers",text:"Chargers for electronics available on board."},{kind:"family",label:"Comfort for children",text:"Baby seat, child seat and booster seat at no additional cost."}];
export const englishDifferentiatorContent: Record<ServiceType | "home", DifferentiatorContent> = {
  home:{eyebrow:"Care in the details",title:"An arrival with",emphasis:"everything in place.",description:"Small gestures that make the journey feel lighter from the very first mile."},
  airport:{eyebrow:"Comfort from touchdown",title:"Your arrival begins",emphasis:"before the hotel.",description:"A service designed to turn the transfer into a warm welcome."}, transfer:{eyebrow:"Hospitality on the road",title:"Traveling through Bahia",emphasis:"can feel effortless.",description:"Thoughtful details between airports, hotels, beaches and villages."}, portoSeguro:{eyebrow:"From airport to destination",title:"The Porto Seguro route",emphasis:"starts cared for.",description:"Comfort and attention for a calm arrival in Trancoso."}, armored:{eyebrow:"Protection with discretion",title:"Security without giving up",emphasis:"comfort.",description:"A reserved operation for those who need an additional layer of protection."}, chauffeur:{eyebrow:"Freedom to move",title:"Your day, without missing",emphasis:"a single detail.",description:"A dedicated vehicle and a chauffeur attuned to the rhythm of your stay."}, concierge:{eyebrow:"Local curation",title:"Trancoso becomes simpler",emphasis:"when someone knows the way.",description:"Local attention for experiences, reservations and special moments."}, events:{eyebrow:"Celebration logistics",title:"Every guest arrives",emphasis:"at the right time.",description:"Coordination and presence so the operation supports the event experience."}, fleet:{eyebrow:"Choose with intention",title:"The right comfort for",emphasis:"the way you travel.",description:"Categories shaped around passengers, luggage and each moment of the journey."},   destinations:{eyebrow:"The route matters too",title:"Bahia reveals itself",emphasis:"in the details of the road.",description:"Support for discovering destinations with time, comfort and local perspective."}, tours:{eyebrow:"A day to discover",title:"The destination deserves",emphasis:"your time.",description:"Private outings with a chauffeur waiting while you experience each place."}, about:{eyebrow:"The Nativos way of welcoming",title:"Knowing the destination means",emphasis:"caring better.",description:"A local operation guided by proximity, discretion and attention."}, booking:{eyebrow:"Before boarding",title:"Your reservation begins",emphasis:"with a conversation.",description:"Tell us what you need and leave the route planning to our team."}, partnerships:{eyebrow:"Operations for partners",title:"Reliability that protects",emphasis:"your guest experience.",description:"A local team that executes every journey with organization and consistency."}
};

export function getLocalizedServiceBySlug(slug: string, locale: Locale = "pt-BR"): LocalizedServiceData | undefined {
  const base = getServiceBySlug(slug);
  if (!base) return undefined;
  if (locale === "pt-BR") return { ...base, locale };
  const copy = englishCopy[base.type];
  return { ...base, ...copy, aliases: [], relatedSlugs: base.relatedSlugs, locale };
}
export function getLocalizedSlugs(locale: Locale = "pt-BR") { return canonicalSlugs.map((slug) => locale === "en" ? `/en/${slug}` : `/${slug}`); }
