// Fonte única de conteúdo: fatos operacionais organizados para jornadas B2C e uma entrada B2B discreta.
export type ServiceType = "airport" | "transfer" | "portoSeguro" | "fleet" | "armored" | "chauffeur" | "concierge" | "events" | "destinations" | "about" | "booking" | "partnerships";
export type Faq = { question: string; answer: string };
export type Differentiator = { kind: "water" | "coconut" | "snacks" | "signal" | "family"; label: string; text: string };
export type ServiceData = { type: ServiceType; slug: string; aliases: string[]; kicker: string; title: string; intro: string; image: string; imageAlt: string; heading: string; body: string; items: string[]; cta: string; faqs: Faq[]; seoTitle?: string; seoDescription?: string; opening?: string; relatedSlugs?: string[]; differentiators?: Differentiator[] };
const img = { hero:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/VtQimewDJyvHxHBP.jpg", arrival:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/bJeJxNaHowAcQwoA.jpg", coast:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/juCISiyVGtGMuEWJ.jpg", interior:"https://files.manuscdn.com/user_upload_by_module/session_file/310419663029716923/fYDlnobOrHYCOWuB.jpg" };
const commonFaqs = [{question:"Como faço uma reserva?",answer:"Envie pelo WhatsApp a data, origem, destino, passageiros, bagagem e, se houver, o número do voo. Um concierge confirma disponibilidade, categoria e valor."},{question:"Vocês atendem crianças?",answer:"Sim. Bebê conforto, cadeirinha e assento elevado podem ser solicitados no momento da reserva."}];
export const differentiators: Differentiator[] = [{kind:"water",label:"H2O",text:"Água mineral a bordo"},{kind:"coconut",label:"COCO",text:"Água de coco para receber você"},{kind:"snacks",label:"PAUSA",text:"Snacks para o caminho"},{kind:"signal",label:"SINAL",text:"Starlink em veículos e rotas compatíveis"},{kind:"family",label:"FAMÍLIA",text:"Bebê conforto e cadeirinha sem custo adicional"}];
export const serviceData: Record<ServiceType, ServiceData> = {
 airport:{type:"airport",slug:"transfer-aeroporto",aliases:["transfer-aeroporto-terravista"],kicker:"TRANSFER · AEROPORTO",title:"Do aeroporto para Trancoso, com tudo já cuidado.",intro:"Recepção privativa no Aeroporto de Porto Seguro, Terravista ou Outeiro das Brisas. Você desembarca. A Nativos faz o resto.",image:img.arrival,imageAlt:"Recepção de passageiros em veículo premium na chegada a Trancoso",heading:"Três portas de entrada.\nUma chegada tranquila.",body:"Atendemos os principais aeroportos da região com motorista local, veículo dedicado e apoio com bagagens. Do Aeroporto de Porto Seguro (BPS) até Trancoso, o trajeto leva de 1h15 a 2h via balsa, ou até 1h20 pela BR-367, rota terrestre sem balsa com cerca de 80 km. Do Aeroporto Terravista (SBTV) até Trancoso são aproximadamente 15 minutos, sem travessia de balsa. O Outeiro das Brisas (SNEC) atende principalmente aviação executiva ou privada com destino à Praia do Espelho e arredores.",items:["Porto Seguro (BPS) — Trancoso · 1h15 a 2h via balsa","Porto Seguro (BPS) — Trancoso · até 1h20 via BR-367","Terravista (SBTV) — Trancoso · cerca de 15 minutos","Outeiro das Brisas (SNEC) · aviação executiva para Praia do Espelho","Monitoramento de voo e motorista aguardando"],cta:"Reservar transfer de aeroporto",faqs:[{question:"Quanto tempo leva de Porto Seguro a Trancoso?",answer:"Via balsa, o trajeto costuma levar de 1h15 a 2h. Pela BR-367, sem balsa, pode levar até 1h20 em cerca de 80 km, conforme as condições da estrada."},{question:"Quanto tempo leva do Terravista até Trancoso?",answer:"O Aeroporto Terravista fica a aproximadamente 15 minutos de Trancoso e não exige travessia de balsa."},{question:"O Outeiro das Brisas atende qual tipo de chegada?",answer:"É uma porta de entrada voltada principalmente à aviação executiva ou privada com destino à Praia do Espelho e arredores."}],},
 
	 portoSeguro:{type:"portoSeguro",slug:"transfer-porto-seguro-trancoso",aliases:[],kicker:"TRANSFER · PORTO SEGURO — TRANCOSO",title:"Do Aeroporto de Porto Seguro a Trancoso, com o caminho já resolvido.",intro:"Transfer privativo entre o Aeroporto de Porto Seguro e Trancoso, com motorista local, apoio com bagagem e escolha de rota conforme o seu horário.",image:img.arrival,imageAlt:"Motorista recebendo viajantes em transfer privativo do Aeroporto de Porto Seguro para Trancoso",heading:"A porta de entrada\npara a sua Bahia.",body:"A Nativos Experiences opera transfers privativos entre o Aeroporto de Porto Seguro e Trancoso. Pela balsa, o trajeto costuma levar de 1h15 a 2h. Pela BR-367, sem travessia, pode levar até 1h20 em aproximadamente 80 km. O tempo varia conforme o trânsito, a balsa e as condições da estrada; a rota é alinhada no atendimento.",items:["Aeroporto de Porto Seguro (BPS) — Trancoso","1h15 a 2h via balsa","Até 1h20 pela BR-367, sem balsa","Motorista local e apoio com bagagens","Monitoramento de voo sob consulta"],cta:"Reservar Porto Seguro — Trancoso",faqs:[{question:"Quanto tempo leva o transfer do Aeroporto de Porto Seguro para Trancoso?",answer:"Via balsa, o trajeto costuma levar de 1h15 a 2h. Pela BR-367, sem balsa, pode levar até 1h20 em aproximadamente 80 km, conforme as condições da estrada."},{question:"A Nativos acompanha o horário do voo?",answer:"O número do voo pode ser enviado no momento da reserva para que a operação seja organizada conforme a chegada prevista."},{question:"Qual rota é usada entre Porto Seguro e Trancoso?",answer:"A rota pode ser feita via balsa ou pela BR-367, sem travessia. A melhor opção é alinhada conforme horário, trânsito e condições do caminho."},{question:"O serviço atende famílias e bagagens?",answer:"Sim. A categoria do veículo é definida conforme passageiros e bagagem; bebê conforto e cadeirinha podem ser solicitados."}],seoTitle:"Transfer Porto Seguro para Trancoso | Nativos Experiences",seoDescription:"Reserve seu transfer privativo do Aeroporto de Porto Seguro para Trancoso. Motorista local, apoio com bagagens e rotas via balsa ou BR-367.",opening:"A Nativos Experiences oferece transfer privativo do Aeroporto de Porto Seguro para Trancoso, na Bahia, com motorista local e apoio desde o desembarque.",relatedSlugs:["transfer-aeroporto","transfer-blindado","motorista-a-disposicao"]},
	 transfer:{type:"transfer",slug:"transfer-trancoso",aliases:[],kicker:"TRANSFER · TRANCOSO E REGIÃO",title:"O caminho até o destino também pode ser leve.",intro:"Transfers privativos entre aeroportos, pousadas, villas, praias e cidades da Costa do Descobrimento.",image:img.coast,imageAlt:"Estrada costeira entre Trancoso e destinos da Bahia",heading:"Você escolhe o lugar.\nA gente conhece o caminho.",body:"De Trancoso a Arraial d’Ajuda, Praia do Espelho, Caraíva, Santo André, Corumbau ou Itacaré. Também cuidamos dos deslocamentos internos: pousada, Quadrado, restaurante, praia ou festa.",items:["Trancoso · Arraial d’Ajuda","Trancoso · Praia do Espelho","Trancoso · Caraíva","Rotas especiais sob consulta"],cta:"Planejar meu trajeto",faqs:[...commonFaqs,{question:"Vocês fazem transfer entre cidades?",answer:"Sim. Organizamos trajetos privativos entre Trancoso, aeroportos, vilas, praias e outros destinos da Bahia sob consulta."}]},
 fleet:{type:"fleet",slug:"frota",aliases:[],kicker:"FROTA · CONFORTO",title:"O carro certo para o jeito que você viaja.",intro:"Dez categorias para diferentes grupos, bagagens e níveis de conforto — sempre com motorista local.",image:img.interior,imageAlt:"Interior confortável de veículo premium para transfer em Trancoso",heading:"Conforto não é excesso.\nÉ poder relaxar.",body:"A categoria é garantida; o modelo de referência pode variar conforme disponibilidade. Consideramos passageiros, bagagem, trajeto e o nível de conforto esperado.",items:["Convencional · Jeep Renegade ou similar · 4 pax","Executiva · Jeep Compass ou similar · 4 pax","Grupo · Chevrolet Spin ou similar · 6 pax","Luxo híbrida · GWM Haval H6 HEV ou similar · 4 pax","Premium · CAOA Chery Tiggo 8 Pro / Jeep Commander · 6 pax","Elite · Toyota SW4 / GWM H9 · 6 pax","Exclusive · BMW iX1 100% elétrica · 4 pax","Van Executiva · Mercedes-Benz Sprinter · até 15 pax","Van Longa · Mercedes-Benz Sprinter Longa · até 19 pax","Blindado · Mercedes-Benz GLE 400d · 4 pax"],cta:"Consultar categoria",faqs:[{question:"A Nativos garante o modelo exato do carro?",answer:"A categoria reservada é considerada na operação. O modelo de referência pode variar conforme disponibilidade e é confirmado antes do serviço."},{question:"Qual veículo atende grupos maiores?",answer:"A Van Executiva atende até 15 passageiros e a Van Longa, até 19 passageiros, conforme configuração e bagagem."},{question:"O blindado faz parte da frota?",answer:"Sim. O Mercedes-Benz GLE 400d blindado está disponível sob demanda, com reserva antecipada recomendada."}]},
 armored:{type:"armored",slug:"transfer-blindado",aliases:["transfer-blindado-trancoso"],kicker:"TRANSFER · BLINDADO",title:"Segurança reforçada, sem abrir mão da discrição.",intro:"O Mercedes-Benz GLE 400d blindado está disponível sob demanda para quem precisa de uma camada adicional de proteção em Trancoso e região.",image:img.hero,imageAlt:"Mercedes-Benz GLE 400d blindado em trajeto na Bahia",heading:"Proteção para seguir\ncom tranquilidade.",body:"Executivos, famílias, artistas, autoridades e eventos podem solicitar o veículo blindado com antecedência. A operação permanece discreta do primeiro embarque ao último retorno.",items:["Mercedes-Benz GLE 400d","Até 4 passageiros","Disponível sob demanda","Reserva antecipada recomendada"],cta:"Solicitar transfer blindado",faqs:[{question:"O blindado precisa de reserva com quanto tempo de antecedência?",answer:"Recomendamos solicitar com antecedência para confirmar a disponibilidade do Mercedes-Benz GLE 400d e organizar a operação com discrição."},{question:"O blindado atende aeroporto e eventos?",answer:"Sim. Pode ser solicitado para transfers de aeroporto, deslocamentos durante a estadia, casamentos e eventos, sempre sob consulta."},{question:"A Nativos é a única empresa da região com esse serviço?",answer:"A Nativos informa que é a única empresa da região a disponibilizar esse serviço. A disponibilidade deve ser confirmada para cada data."}]},
 chauffeur:{type:"chauffeur",slug:"motorista-a-disposicao",aliases:[],kicker:"MOTORISTA À DISPOSIÇÃO",title:"Seu dia, no seu ritmo.",intro:"Um motorista particular e um veículo dedicado para você circular sem depender de horários ou negociar cada trajeto.",image:img.arrival,imageAlt:"Motorista local aguardando passageiros em hospedagem de Trancoso",heading:"Mais tempo para viver.\nMenos tempo organizando.",body:"Escolha o período que faz sentido para a sua estadia: 4h, 8h, 12h ou 24h. O motorista leva, aguarda e retorna quando você decidir.",items:["Períodos de 4h, 8h, 12h ou 24h","Veículo 100% dedicado","Motorista local e discreto","Ideal para praias, restaurantes e eventos"],cta:"Consultar motorista à disposição",faqs:[...commonFaqs,{question:"O motorista fica disponível durante todo o período contratado?",answer:"Sim. O veículo e o motorista ficam dedicados ao seu grupo durante o período escolhido, dentro do roteiro combinado."}]},
 concierge:{type:"concierge",slug:"concierge-trancoso",aliases:["concierge"],kicker:"CONCIERGE · TRANCOSO",title:"Para viver Trancoso sem perder tempo procurando.",intro:"Restaurantes, praias, barcos, villas e experiências escolhidas para os seus dias — com um concierge que conhece a região por dentro.",image:img.coast,imageAlt:"Praia e paisagem da Costa do Descobrimento para planejar experiências em Trancoso",heading:"O que você quiser viver.\nA gente ajuda a acontecer.",body:"Do jantar na villa ao passeio de barco, do chef particular à massagem depois da praia. O concierge Nativos coordena os detalhes da sua estadia com olhar local e uma conversa direta pelo WhatsApp.",items:["Restaurantes e beach clubs","Barcos, praias e passeios privativos","Chef, compras e serviços para a villa","Bem-estar, beleza e experiências"],cta:"Falar com concierge",faqs:[...commonFaqs,{question:"O concierge também organiza reservas?",answer:"Sim. Conte o que deseja viver em Trancoso e o concierge orienta e coordena as possibilidades disponíveis para a sua estadia."}]},
 events:{type:"events",slug:"casamentos-e-eventos",aliases:[],kicker:"CASAMENTOS E EVENTOS",title:"A celebração merece uma chegada à altura.",intro:"Transporte de convidados, noivos, artistas e staff para casamentos, festas privadas e eventos em Trancoso e região.",image:img.hero,imageAlt:"Veículo premium preparado para transporte de convidados em evento na Bahia",heading:"O seu evento acontece.\nA logística fica com a gente.",body:"Coordenamos vans, SUVs, veículos especiais e horários escalonados para que cada convidado saiba onde embarcar e chegue no tempo certo.",items:["Casamentos íntimos e grandes celebrações","Transporte de convidados e padrinhos","Artistas, staff, fornecedores e equipamentos","Vans, apoio e blindado sob consulta"],cta:"Solicitar orçamento de evento",faqs:[...commonFaqs,{question:"A Nativos atende casamentos em Trancoso?",answer:"Sim. Organizamos o transporte de convidados, noivos, padrinhos, artistas e equipes para casamentos e festas privadas."},{question:"É possível organizar horários diferentes para os convidados?",answer:"Sim. Trabalhamos com horários escalonados e pontos de embarque previamente combinados para facilitar a logística do evento."}]},
 destinations:{type:"destinations",slug:"destinos",aliases:[],kicker:"DESTINOS · BAHIA",title:"Trancoso é o ponto de partida.",intro:"Praias, vilas e caminhos da Costa do Descobrimento para descobrir com um motorista que sabe quando ir — e por onde.",image:img.coast,imageAlt:"Praia na Costa do Descobrimento próxima a Trancoso",heading:"A Bahia tem muitos ritmos.\nEscolha o seu.",body:"Faça um passeio de dia inteiro, combine uma praia com um almoço ou crie uma rota entre destinos. Itacaré é para quem quer estender a viagem além da Costa do Descobrimento, não um bate-volta de Trancoso.",items:["Trancoso · Quadrado, praias e villas","Arraial d’Ajuda · história e mirantes","Praia do Espelho · praia e almoço","Caraíva, Santo André e Corumbau","Itacaré · extensão da viagem pela Bahia"],cta:"Escolher meu destino",faqs:[...commonFaqs,{question:"Itacaré é perto de Trancoso?",answer:"Não é um bate-volta próximo. Itacaré fica em outra região da Bahia e faz sentido para quem deseja estender a viagem além da Costa do Descobrimento."}]},
 about:{type:"about",slug:"sobre-nativos",aliases:["sobre"],kicker:"SOBRE · NATIVOS EXPERIENCES",title:"Nascemos em Trancoso para fazer você se sentir em casa.",intro:"Desde 2015, cuidamos de chegadas, deslocamentos e detalhes de estadias com discrição, pontualidade e conhecimento local.",image:img.arrival,imageAlt:"Chegada acolhedora de viajantes em hospedagem de Trancoso",heading:"Conhecer o destino\né cuidar melhor.",body:"A Nativos nasceu levando amigos do aeroporto ao Quadrado. Hoje, uma equipe local atende famílias, viajantes, executivos e eventos que valorizam a tranquilidade de ter alguém de confiança no caminho.",items:["Atendimento privativo, um cliente por vez","Motoristas locais e discretos","Curadoria de quem vive em Trancoso","Suporte pessoal pelo WhatsApp"],cta:"Conversar com a Nativos",faqs:[...commonFaqs,{question:"Onde a Nativos Experiences está situada?",answer:"A Nativos Experiences está situada em Trancoso, Bahia, com atendimento local para transfers e serviços de hospitalidade na região."}]},
 booking:{type:"booking",slug:"reserva-online",aliases:["reserva"],kicker:"RESERVA · NATIVOS EXPERIENCES",title:"Sua chegada começa com uma conversa.",intro:"Envie o voo, a hospedagem e o que você precisa. Um concierge confirma veículo, motorista, disponibilidade e valor.",image:img.interior,imageAlt:"Detalhe de conforto no interior de veículo para reserva em Trancoso",heading:"Você informa os detalhes.\nA gente cuida do caminho.",body:"Para solicitar um transfer, conte a origem, o destino, a data, o horário, o número de passageiros e a bagagem. Se houver voo, envie o número para acompanharmos a chegada.",items:["Transfer de aeroporto ou entre cidades","Motorista à disposição","Concierge e experiências","Eventos e casamentos"],cta:"Abrir reserva no WhatsApp",faqs:[...commonFaqs,{question:"Quais informações devo enviar para reservar?",answer:"Informe origem, destino, data, horário, passageiros, bagagem, hospedagem e o número do voo, se houver."}]},
 partnerships:{type:"partnerships",slug:"parcerias",aliases:[],kicker:"PARCERIAS · NATIVOS EXPERIENCES",title:"Uma operação local para cuidar dos seus hóspedes.",intro:"Transfer, motorista e concierge para hotéis, pousadas, villas, imobiliárias, agências, DMCs, cerimonialistas e produtoras de evento.",image:img.hero,imageAlt:"Veículo premium preparado para atender hóspedes e eventos em Trancoso",heading:"Você cuida da experiência.\nA gente sustenta o caminho.",body:"A Nativos apoia parceiros que precisam de uma operação recorrente, comunicação organizada e atendimento próximo em Trancoso e região. O escopo pode incluir transfers, motoristas à disposição, eventos, casamentos e concierge. O comissionamento e o formato de trabalho são alinhados caso a caso, sem tabela pública.",items:["Hotéis, pousadas e villas","Imobiliárias, agências e DMCs","Cerimonialistas e produtoras de eventos","Ponto de contato dedicado","Operação recorrente sob alinhamento"],cta:"Falar sobre parceria",faqs:[{question:"Com quais parceiros a Nativos trabalha?",answer:"Atendemos hotéis, pousadas, villas, imobiliárias, agências de viagem, DMCs, cerimonialistas e produtoras de eventos."},{question:"Existe comissionamento para parceiros?",answer:"O formato comercial é alinhado caso a caso, conforme o escopo e a recorrência da operação. Não trabalhamos com números públicos nesta página."},{question:"Como começo uma parceria?",answer:"Envie pelo WhatsApp o nome da empresa, o tipo de operação e o volume aproximado de atendimento. Um ponto de contato retorna para conversar."}]}
};
const pageOverrides: Partial<Record<ServiceType, Partial<ServiceData>>> = {
  armored: {
    title:"Transfer blindado em Porto Seguro e Trancoso, com discrição.",
    intro:"A Nativos Experiences opera o único veículo blindado disponível para transfer executivo na região de Porto Seguro e Trancoso: um Mercedes-Benz GLE 400d blindado.",
    opening:"A Nativos Experiences opera o único veículo blindado disponível para transfer executivo na região de Porto Seguro e Trancoso: um Mercedes-Benz GLE 400d blindado.",
    body:"O serviço foi pensado para executivos, autoridades, artistas, famílias que buscam discrição e eventos de alto perfil. A reserva é feita com antecedência recomendada, definição da região atendida e alinhamento do ponto de embarque, horário e rota. O motorista conduz a operação com discrição do aeroporto ao hotel, entre compromissos ou durante um evento.",
    items:["Mercedes-Benz GLE 400d blindado","Único blindado do segmento na região","Transfer de aeroporto, hotel e eventos","Motorista discreto e operação sob demanda","Reserva antecipada recomendada"],
    cta:"Solicitar transfer blindado",
    seoTitle:"Transfer Blindado Porto Seguro e Trancoso | Nativos Experiences",
    seoDescription:"Transfer blindado em Porto Seguro e Trancoso com Mercedes-Benz GLE 400d. Serviço sob demanda para executivos, famílias, autoridades, artistas e eventos.",
    relatedSlugs:["casamentos-e-eventos","motorista-a-disposicao","transfer-porto-seguro-trancoso"],
    faqs:[{question:"O blindado atende no aeroporto?",answer:"Sim. O Mercedes-Benz GLE 400d pode ser solicitado para chegada ou saída pelo Aeroporto de Porto Seguro, Aeroporto Terravista e outras portas de entrada atendidas sob consulta."},{question:"Qual é o nível de blindagem?",answer:"O nível de blindagem deve ser confirmado no atendimento para a configuração disponível na data solicitada."},{question:"Preciso reservar com quanto tempo de antecedência?",answer:"A reserva antecipada é recomendada para confirmar a disponibilidade do veículo e organizar a operação com discrição."},{question:"O serviço atende fora de Trancoso?",answer:"Sim. O atendimento pode contemplar Porto Seguro, Trancoso e outros pontos da Costa do Descobrimento, conforme rota e disponibilidade."}]
  },
  events: {
    opening:"A Nativos Experiences coordena transporte premium para casamentos, festas privadas, festivais e eventos em Trancoso e região, atendendo convidados, noivos, artistas, staff e fornecedores.",
    body:"Para casais e cerimonialistas, organizamos a chegada dos convidados, padrinhos e noivos com horários e pontos de embarque alinhados ao roteiro da celebração. Para produtoras e agências, executamos a logística de convidados, artistas, staff, fornecedores e equipamentos mantendo o padrão de atendimento definido pelo parceiro. A operação pode envolver vans, SUVs, veículos especiais e blindado sob consulta.",
    items:["Casamentos íntimos e grandes celebrações","Festas privadas e festivais","Convidados, noivos, artistas e staff","Cerimonialistas e wedding planners","Produtoras, agências e fornecedores","Vans, SUVs e blindado sob consulta"],
    seoTitle:"Transfer para Casamentos e Eventos em Trancoso | Nativos Experiences",
    seoDescription:"Transporte premium para casamentos, festas privadas, festivais e eventos em Trancoso. Logística de convidados, noivos, artistas, staff e fornecedores.",
    relatedSlugs:["transfer-blindado","motorista-a-disposicao","concierge-trancoso"],
    faqs:[{question:"A Nativos atende casamentos em Trancoso?",answer:"Sim. Coordenamos transporte de convidados, noivos, padrinhos, artistas e equipes para casamentos e celebrações na região."},{question:"Como funciona a logística para cerimonialistas?",answer:"Alinhamos roteiro, horários, pontos de embarque e categorias de veículos para executar a operação mantendo o padrão de atendimento definido pelo evento ou parceiro."},{question:"A empresa atende produtoras e agências?",answer:"Sim. Produtoras e agências podem solicitar logística para convidados, artistas, staff, fornecedores e equipamentos, conforme escopo do evento."},{question:"É possível solicitar blindado para um evento?",answer:"Sim. O veículo blindado pode ser solicitado sob consulta, com reserva antecipada recomendada para confirmar disponibilidade."}]
  },
  chauffeur: {
    opening:"A Nativos Experiences oferece motorista particular em Trancoso, Porto Seguro e região, com veículo dedicado para quem deseja circular pela Bahia sem depender de horários ou organizar cada trajeto.",
    body:"O serviço é indicado para famílias, executivos, casais e grupos que desejam liberdade durante a estadia. O motorista busca, aguarda e retorna conforme o roteiro combinado, seja para praias, restaurantes, villas, eventos ou compromissos. Os períodos de 4h, 8h, 12h ou 24h são definidos conforme a necessidade e a disponibilidade.",
    seoTitle:"Motorista Particular em Trancoso e Porto Seguro | Nativos Experiences",
    seoDescription:"Motorista particular em Trancoso e Porto Seguro com veículo dedicado. Reserve por 4h, 8h, 12h ou 24h para praias, restaurantes, eventos e passeios.",
    relatedSlugs:["transfer-porto-seguro-trancoso","concierge-trancoso","casamentos-e-eventos"]
  }
};
export const allSlugs = Object.values(serviceData).flatMap((item) => [item.slug, ...item.aliases]);
export function getServiceBySlug(slug: string) { const item = Object.values(serviceData).find((entry) => entry.slug === slug || entry.aliases.includes(slug)); return item ? { ...item, ...pageOverrides[item.type] } : undefined; }
