// Casa de Areia: páginas internas SSR para capturar buscas específicas e levar o visitante à reserva.
import type { Metadata } from "next";
import { Footer, Header, partnershipWhatsapp, whatsapp, WhatsAppButton } from "@/components/SiteChrome";
import { allSlugs, getServiceBySlug } from "@/lib/data";

export function generateStaticParams() { return allSlugs.map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const page = getServiceBySlug(slug); if (!page) return {}; return { title: page.title, description: page.intro, alternates: { canonical: `/${page.slug}` }, openGraph: { title: page.title, description: page.intro, images: [{ url: page.image }] } }; }

export default async function ServiceRoute({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const page = getServiceBySlug(slug); if (!page) return <main className="section-light" style={{ minHeight: "100vh", padding: "12vw" }}><h1>Página não encontrada</h1><a href="/">Voltar</a></main>; const jsonLd = { "@context":"https://schema.org", "@type":"Service", name:page.title, description:page.intro, provider:{"@type":"TravelAgency",name:"Nativos Experiences",url:"https://nativosexperiences.com/"}, areaServed:{"@type":"Place",name:"Trancoso, Bahia"}, url:`https://nativosexperiences.com/${page.slug}` }; return <main className="service-page sand-theme"><Header /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><section className="service-hero"><img src={page.image} alt={page.imageAlt} /><div className="service-hero-shade" /><div className="service-hero-content"><a href="/" className="back-link">Voltar à Nativos</a><p className="eyebrow light"><span className="eyebrow-dot" /> {page.kicker}</p><h1>{page.title}</h1><p>{page.intro}</p><a className="hero-action" href={page.type === "partnerships" ? partnershipWhatsapp : whatsapp} target="_blank" rel="noreferrer">{page.cta}</a></div></section><section className="service-body section-light"><div className="service-body-grid"><div className="service-copy"><p className="eyebrow dark"><span className="eyebrow-dot" /> Nativos Experiences · Trancoso</p><h2>{page.heading.split("\n").map((line, index) => <span key={line}>{line}{index === 0 && <br />}</span>)}</h2><p>{page.body}</p><WhatsAppButton label={page.cta} href={page.type === "partnerships" ? partnershipWhatsapp : whatsapp} /></div><div className="service-facts"><span className="facts-label">O que você pode esperar</span>{page.items.map((item, index) => <div className="service-fact" key={item}><span>0{index+1}</span><strong>{item}</strong></div>)}</div></div><div className="service-faqs"><span className="facts-label">Perguntas frequentes</span>{page.faqs.map((faq) => <details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</div></section><Footer /></main>; }
